// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DirectChat struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DirectChatMessage struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID   uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind           string             `db:"kind" json:"kind"`
	TextContent    string             `db:"text_content" json:"text_content"`
	MarkdownPolicy string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DirectChatMessageTombstone struct {
	MessageID       uuid.UUID          `db:"message_id" json:"message_id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	DeletedByUserID uuid.UUID          `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type DirectChatParticipant struct {
	ChatID   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type DirectChatPin struct {
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	Login                   string             `db:"login" json:"login"`
	Nickname                string             `db:"nickname" json:"nickname"`
	AvatarUrl               pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                     pgtype.Text        `db:"bio" json:"bio"`
	Timezone                pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent           pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText              pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                pgtype.Date        `db:"birthday" json:"birthday"`
	Country                 pgtype.Text        `db:"country" json:"country"`
	City                    pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled     bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled         bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus         string             `db:"key_backup_status" json:"key_backup_status"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserBlock struct {
	BlockerUserID uuid.UUID          `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID          `db:"blocked_user_id" json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserDevice struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Label      string             `db:"label" json:"label"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type UserFriendRequest struct {
	RequesterUserID uuid.UUID          `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID uuid.UUID          `db:"addressee_user_id" json:"addressee_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserFriendship struct {
	UserLowID  uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPasswordCredential struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}
