// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatsqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDirectChatParticipant(ctx context.Context, arg AddDirectChatParticipantParams) error
	AddGroupMembership(ctx context.Context, arg AddGroupMembershipParams) error
	AttachDirectMessageAttachment(ctx context.Context, arg AttachDirectMessageAttachmentParams) error
	AttachGroupMessageAttachment(ctx context.Context, arg AttachGroupMessageAttachmentParams) error
	CompleteAttachmentUpload(ctx context.Context, arg CompleteAttachmentUploadParams) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (CreateAttachmentRow, error)
	CreateAttachmentUploadSession(ctx context.Context, arg CreateAttachmentUploadSessionParams) (AttachmentUploadSession, error)
	CreateDirectChat(ctx context.Context, arg CreateDirectChatParams) (DirectChat, error)
	CreateDirectChatEncryptedMessageV2(ctx context.Context, arg CreateDirectChatEncryptedMessageV2Params) (DirectChatEncryptedMessagesV2, error)
	CreateDirectChatEncryptedMessageV2Delivery(ctx context.Context, arg CreateDirectChatEncryptedMessageV2DeliveryParams) error
	CreateDirectChatMessage(ctx context.Context, arg CreateDirectChatMessageParams) (CreateDirectChatMessageRow, error)
	CreateDirectChatMessageTombstone(ctx context.Context, arg CreateDirectChatMessageTombstoneParams) (int64, error)
	CreateEncryptedGroupLane(ctx context.Context, arg CreateEncryptedGroupLaneParams) (GroupEncryptedLanesV1, error)
	CreateEncryptedGroupMessage(ctx context.Context, arg CreateEncryptedGroupMessageParams) (CreateEncryptedGroupMessageRow, error)
	CreateEncryptedGroupMessageDelivery(ctx context.Context, arg CreateEncryptedGroupMessageDeliveryParams) error
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupInviteLink(ctx context.Context, arg CreateGroupInviteLinkParams) (CreateGroupInviteLinkRow, error)
	CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (CreateGroupMessageRow, error)
	CreateGroupThread(ctx context.Context, arg CreateGroupThreadParams) (GroupThread, error)
	DeleteEncryptedGroupRosterDevicesByGroupID(ctx context.Context, groupID uuid.UUID) error
	DeleteEncryptedGroupRosterMembersByGroupID(ctx context.Context, groupID uuid.UUID) error
	DeleteGroupMembership(ctx context.Context, arg DeleteGroupMembershipParams) (int64, error)
	DetachDirectMessageAttachments(ctx context.Context, arg DetachDirectMessageAttachmentsParams) (int64, error)
	DisableGroupInviteLink(ctx context.Context, arg DisableGroupInviteLinkParams) (int64, error)
	EditDirectChatMessageText(ctx context.Context, arg EditDirectChatMessageTextParams) (int64, error)
	EditGroupMessageText(ctx context.Context, arg EditGroupMessageTextParams) (int64, error)
	ExpireAttachmentUploadSession(ctx context.Context, arg ExpireAttachmentUploadSessionParams) (int64, error)
	ExpireOrphanUploadedAttachments(ctx context.Context, arg ExpireOrphanUploadedAttachmentsParams) (int64, error)
	ExpirePendingAttachmentUploadSessions(ctx context.Context, arg ExpirePendingAttachmentUploadSessionsParams) (int64, error)
	FailAttachmentUpload(ctx context.Context, arg FailAttachmentUploadParams) (int64, error)
	FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error)
	GetActiveGroupMembershipCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	GetAttachmentQuotaUsageByOwner(ctx context.Context, ownerUserID uuid.UUID) (int64, error)
	GetAttachmentRowByID(ctx context.Context, id uuid.UUID) (GetAttachmentRowByIDRow, error)
	GetDirectChatEncryptedMessageV2ByDevice(ctx context.Context, arg GetDirectChatEncryptedMessageV2ByDeviceParams) (GetDirectChatEncryptedMessageV2ByDeviceRow, error)
	GetDirectChatEncryptedMessageV2Stored(ctx context.Context, arg GetDirectChatEncryptedMessageV2StoredParams) (DirectChatEncryptedMessagesV2, error)
	GetDirectChatMessageByID(ctx context.Context, arg GetDirectChatMessageByIDParams) (GetDirectChatMessageByIDRow, error)
	GetDirectChatRelationshipState(ctx context.Context, arg GetDirectChatRelationshipStateParams) (GetDirectChatRelationshipStateRow, error)
	GetDirectChatRowsByIDAndUserID(ctx context.Context, arg GetDirectChatRowsByIDAndUserIDParams) ([]GetDirectChatRowsByIDAndUserIDRow, error)
	GetEncryptedGroupLaneByGroupID(ctx context.Context, groupID uuid.UUID) (GroupEncryptedLanesV1, error)
	GetEncryptedGroupMessageByDevice(ctx context.Context, arg GetEncryptedGroupMessageByDeviceParams) (GetEncryptedGroupMessageByDeviceRow, error)
	GetEncryptedGroupReadStateEntryByGroupIDAndUserID(ctx context.Context, arg GetEncryptedGroupReadStateEntryByGroupIDAndUserIDParams) (GetEncryptedGroupReadStateEntryByGroupIDAndUserIDRow, error)
	GetEncryptedGroupStoredMessage(ctx context.Context, arg GetEncryptedGroupStoredMessageParams) (GetEncryptedGroupStoredMessageRow, error)
	GetGroupChatThreadRowByGroupIDAndUserID(ctx context.Context, arg GetGroupChatThreadRowByGroupIDAndUserIDParams) (GroupThread, error)
	GetGroupInviteLinkByIDAndGroupID(ctx context.Context, arg GetGroupInviteLinkByIDAndGroupIDParams) (GetGroupInviteLinkByIDAndGroupIDRow, error)
	GetGroupInviteLinkForJoin(ctx context.Context, tokenHash string) (GetGroupInviteLinkForJoinRow, error)
	GetGroupMemberRowByGroupIDAndUserID(ctx context.Context, arg GetGroupMemberRowByGroupIDAndUserIDParams) (GetGroupMemberRowByGroupIDAndUserIDRow, error)
	GetGroupMessageByIDAndUserID(ctx context.Context, arg GetGroupMessageByIDAndUserIDParams) (GetGroupMessageByIDAndUserIDRow, error)
	GetGroupReadStateEntryByGroupIDAndUserID(ctx context.Context, arg GetGroupReadStateEntryByGroupIDAndUserIDParams) (GetGroupReadStateEntryByGroupIDAndUserIDRow, error)
	GetGroupRowByIDAndUserID(ctx context.Context, arg GetGroupRowByIDAndUserIDParams) (GetGroupRowByIDAndUserIDRow, error)
	GetSessionAuthByID(ctx context.Context, id uuid.UUID) (GetSessionAuthByIDRow, error)
	InsertEncryptedGroupRosterDevice(ctx context.Context, arg InsertEncryptedGroupRosterDeviceParams) error
	InsertEncryptedGroupRosterMember(ctx context.Context, arg InsertEncryptedGroupRosterMemberParams) error
	JoinGroupMembership(ctx context.Context, arg JoinGroupMembershipParams) (int64, error)
	ListActiveCryptoDevicesByUserIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListActiveCryptoDevicesByUserIDsRow, error)
	ListAttachmentObjectDeletionCandidates(ctx context.Context, arg ListAttachmentObjectDeletionCandidatesParams) ([]ListAttachmentObjectDeletionCandidatesRow, error)
	ListAttachmentRowsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListAttachmentRowsByIDsRow, error)
	ListCurrentCryptoDeviceBundlesByDeviceIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCurrentCryptoDeviceBundlesByDeviceIDsRow, error)
	ListDirectChatEncryptedMessageV2ByDevice(ctx context.Context, arg ListDirectChatEncryptedMessageV2ByDeviceParams) ([]ListDirectChatEncryptedMessageV2ByDeviceRow, error)
	ListDirectChatMessages(ctx context.Context, arg ListDirectChatMessagesParams) ([]ListDirectChatMessagesRow, error)
	ListDirectChatPresenceStateEntries(ctx context.Context, arg ListDirectChatPresenceStateEntriesParams) ([]ListDirectChatPresenceStateEntriesRow, error)
	ListDirectChatReadStateEntries(ctx context.Context, arg ListDirectChatReadStateEntriesParams) ([]ListDirectChatReadStateEntriesRow, error)
	ListDirectChatRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListDirectChatRowsByUserIDRow, error)
	ListDirectChatTypingStateEntries(ctx context.Context, arg ListDirectChatTypingStateEntriesParams) ([]ListDirectChatTypingStateEntriesRow, error)
	ListDirectMessageAttachmentRowsByMessageIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListDirectMessageAttachmentRowsByMessageIDsRow, error)
	ListDirectReplyPreviewRows(ctx context.Context, arg ListDirectReplyPreviewRowsParams) ([]ListDirectReplyPreviewRowsRow, error)
	ListEncryptedDirectChatReadStateEntries(ctx context.Context, arg ListEncryptedDirectChatReadStateEntriesParams) ([]ListEncryptedDirectChatReadStateEntriesRow, error)
	ListEncryptedGroupMessagesByDevice(ctx context.Context, arg ListEncryptedGroupMessagesByDeviceParams) ([]ListEncryptedGroupMessagesByDeviceRow, error)
	ListEncryptedGroupRosterDevicesByGroupID(ctx context.Context, groupID uuid.UUID) ([]GroupEncryptedRosterDevicesV1, error)
	ListEncryptedGroupRosterMembersByGroupID(ctx context.Context, groupID uuid.UUID) ([]GroupEncryptedRosterMembersV1, error)
	ListEncryptedPinnedMessageIDsByChatID(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error)
	ListEncryptedPinnedMessageIDsByGroupID(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error)
	ListGroupInviteLinksByGroupID(ctx context.Context, groupID uuid.UUID) ([]ListGroupInviteLinksByGroupIDRow, error)
	ListGroupMemberRowsByGroupIDAndUserID(ctx context.Context, arg ListGroupMemberRowsByGroupIDAndUserIDParams) ([]ListGroupMemberRowsByGroupIDAndUserIDRow, error)
	ListGroupMessageAttachmentRowsByMessageIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ListGroupMessageAttachmentRowsByMessageIDsRow, error)
	ListGroupMessagesByGroupIDAndUserID(ctx context.Context, arg ListGroupMessagesByGroupIDAndUserIDParams) ([]ListGroupMessagesByGroupIDAndUserIDRow, error)
	ListGroupReplyPreviewRows(ctx context.Context, arg ListGroupReplyPreviewRowsParams) ([]ListGroupReplyPreviewRowsRow, error)
	ListGroupRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListGroupRowsByUserIDRow, error)
	ListGroupTypingStateEntries(ctx context.Context, arg ListGroupTypingStateEntriesParams) ([]ListGroupTypingStateEntriesRow, error)
	ListPinnedMessageIDsByChatID(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error)
	LockAttachmentQuotaOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockGroupByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	LockGroupMembershipQuotaOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	MarkAttachmentAttached(ctx context.Context, arg MarkAttachmentAttachedParams) (int64, error)
	MarkAttachmentDeleted(ctx context.Context, arg MarkAttachmentDeletedParams) (int64, error)
	PinDirectChatMessage(ctx context.Context, arg PinDirectChatMessageParams) (int64, error)
	PinEncryptedDirectMessageV2(ctx context.Context, arg PinEncryptedDirectMessageV2Params) (int64, error)
	PinEncryptedGroupMessage(ctx context.Context, arg PinEncryptedGroupMessageParams) (int64, error)
	SearchDirectMessages(ctx context.Context, arg SearchDirectMessagesParams) ([]SearchDirectMessagesRow, error)
	SearchGroupMessages(ctx context.Context, arg SearchGroupMessagesParams) ([]SearchGroupMessagesRow, error)
	SetGroupMembershipWriteRestriction(ctx context.Context, arg SetGroupMembershipWriteRestrictionParams) (int64, error)
	TouchDirectChatMessageUpdatedAt(ctx context.Context, arg TouchDirectChatMessageUpdatedAtParams) error
	TouchDirectChatUpdatedAt(ctx context.Context, arg TouchDirectChatUpdatedAtParams) error
	TouchGroupInviteLinkJoin(ctx context.Context, arg TouchGroupInviteLinkJoinParams) error
	TouchGroupThreadUpdatedAt(ctx context.Context, arg TouchGroupThreadUpdatedAtParams) error
	TouchGroupUpdatedAt(ctx context.Context, arg TouchGroupUpdatedAtParams) error
	TouchSessionAndDevice(ctx context.Context, arg TouchSessionAndDeviceParams) error
	TransferGroupOwnership(ctx context.Context, arg TransferGroupOwnershipParams) (int64, error)
	UnpinDirectChatMessage(ctx context.Context, arg UnpinDirectChatMessageParams) (int64, error)
	UnpinEncryptedDirectMessageV2(ctx context.Context, arg UnpinEncryptedDirectMessageV2Params) (int64, error)
	UnpinEncryptedGroupMessage(ctx context.Context, arg UnpinEncryptedGroupMessageParams) (int64, error)
	UpdateEncryptedGroupLane(ctx context.Context, arg UpdateEncryptedGroupLaneParams) (int64, error)
	UpdateGroupMembershipRole(ctx context.Context, arg UpdateGroupMembershipRoleParams) (int64, error)
	UpsertDirectChatReadReceipt(ctx context.Context, arg UpsertDirectChatReadReceiptParams) (int64, error)
	UpsertEncryptedDirectChatReadState(ctx context.Context, arg UpsertEncryptedDirectChatReadStateParams) (int64, error)
	UpsertEncryptedGroupReadState(ctx context.Context, arg UpsertEncryptedGroupReadStateParams) (int64, error)
	UpsertGroupChatReadState(ctx context.Context, arg UpsertGroupChatReadStateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
