// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package chatsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDirectChatParticipant = `-- name: AddDirectChatParticipant :exec
INSERT INTO direct_chat_participants (
    chat_id,
    user_id,
    joined_at
) VALUES ($1, $2, $3)
`

type AddDirectChatParticipantParams struct {
	ChatID   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) AddDirectChatParticipant(ctx context.Context, arg AddDirectChatParticipantParams) error {
	_, err := q.db.Exec(ctx, addDirectChatParticipant, arg.ChatID, arg.UserID, arg.JoinedAt)
	return err
}

const addGroupMembership = `-- name: AddGroupMembership :exec
INSERT INTO group_memberships (
    group_id,
    user_id,
    role,
    joined_at
) VALUES ($1, $2, $3, $4)
`

type AddGroupMembershipParams struct {
	GroupID  uuid.UUID          `db:"group_id" json:"group_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) AddGroupMembership(ctx context.Context, arg AddGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, addGroupMembership,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createDirectChat = `-- name: CreateDirectChat :one
INSERT INTO direct_chats (
    id,
    created_by_user_id,
    user_low_id,
    user_high_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_by_user_id, user_low_id, user_high_id, created_at, updated_at
`

type CreateDirectChatParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDirectChat(ctx context.Context, arg CreateDirectChatParams) (DirectChat, error) {
	row := q.db.QueryRow(ctx, createDirectChat,
		arg.ID,
		arg.CreatedByUserID,
		arg.UserLowID,
		arg.UserHighID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DirectChat
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.UserLowID,
		&i.UserHighID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectChatMessage = `-- name: CreateDirectChatMessage :one
INSERT INTO direct_chat_messages (
    id,
    chat_id,
    sender_user_id,
    kind,
    text_content,
    markdown_policy,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chat_id, sender_user_id, kind, text_content, markdown_policy, created_at, updated_at
`

type CreateDirectChatMessageParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID   uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind           string             `db:"kind" json:"kind"`
	TextContent    string             `db:"text_content" json:"text_content"`
	MarkdownPolicy string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDirectChatMessage(ctx context.Context, arg CreateDirectChatMessageParams) (DirectChatMessage, error) {
	row := q.db.QueryRow(ctx, createDirectChatMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderUserID,
		arg.Kind,
		arg.TextContent,
		arg.MarkdownPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DirectChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderUserID,
		&i.Kind,
		&i.TextContent,
		&i.MarkdownPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectChatMessageTombstone = `-- name: CreateDirectChatMessageTombstone :execrows
INSERT INTO direct_chat_message_tombstones (
    message_id,
    chat_id,
    deleted_by_user_id,
    deleted_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id) DO NOTHING
`

type CreateDirectChatMessageTombstoneParams struct {
	MessageID       uuid.UUID          `db:"message_id" json:"message_id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	DeletedByUserID uuid.UUID          `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) CreateDirectChatMessageTombstone(ctx context.Context, arg CreateDirectChatMessageTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDirectChatMessageTombstone,
		arg.MessageID,
		arg.ChatID,
		arg.DeletedByUserID,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    id,
    name,
    created_by_user_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, created_by_user_id, created_at, updated_at
`

type CreateGroupParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupInviteLink = `-- name: CreateGroupInviteLink :one
INSERT INTO group_invite_links (
    id,
    group_id,
    created_by_user_id,
    role,
    token_hash,
    join_count,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, 0, $6, $7)
RETURNING id, group_id, created_by_user_id, role, join_count, created_at, updated_at, disabled_at, last_joined_at
`

type CreateGroupInviteLinkParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role            string             `db:"role" json:"role"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CreateGroupInviteLinkRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role            string             `db:"role" json:"role"`
	JoinCount       int32              `db:"join_count" json:"join_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastJoinedAt    pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
}

func (q *Queries) CreateGroupInviteLink(ctx context.Context, arg CreateGroupInviteLinkParams) (CreateGroupInviteLinkRow, error) {
	row := q.db.QueryRow(ctx, createGroupInviteLink,
		arg.ID,
		arg.GroupID,
		arg.CreatedByUserID,
		arg.Role,
		arg.TokenHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateGroupInviteLinkRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Role,
		&i.JoinCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.LastJoinedAt,
	)
	return i, err
}

const createGroupMessage = `-- name: CreateGroupMessage :one
INSERT INTO group_messages (
    id,
    thread_id,
    sender_user_id,
    kind,
    text_content,
    markdown_policy,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, thread_id, sender_user_id, kind, text_content, markdown_policy, created_at, updated_at
`

type CreateGroupMessageParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ThreadID       uuid.UUID          `db:"thread_id" json:"thread_id"`
	SenderUserID   uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind           string             `db:"kind" json:"kind"`
	TextContent    string             `db:"text_content" json:"text_content"`
	MarkdownPolicy string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateGroupMessage(ctx context.Context, arg CreateGroupMessageParams) (GroupMessage, error) {
	row := q.db.QueryRow(ctx, createGroupMessage,
		arg.ID,
		arg.ThreadID,
		arg.SenderUserID,
		arg.Kind,
		arg.TextContent,
		arg.MarkdownPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GroupMessage
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.SenderUserID,
		&i.Kind,
		&i.TextContent,
		&i.MarkdownPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupThread = `-- name: CreateGroupThread :one
INSERT INTO group_threads (
    id,
    group_id,
    thread_key,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, thread_key, created_at, updated_at
`

type CreateGroupThreadParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	GroupID   uuid.UUID          `db:"group_id" json:"group_id"`
	ThreadKey string             `db:"thread_key" json:"thread_key"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateGroupThread(ctx context.Context, arg CreateGroupThreadParams) (GroupThread, error) {
	row := q.db.QueryRow(ctx, createGroupThread,
		arg.ID,
		arg.GroupID,
		arg.ThreadKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GroupThread
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableGroupInviteLink = `-- name: DisableGroupInviteLink :execrows
UPDATE group_invite_links
SET
    disabled_at = $3,
    updated_at = $3
WHERE group_id = $1 AND id = $2 AND disabled_at IS NULL
`

type DisableGroupInviteLinkParams struct {
	GroupID    uuid.UUID          `db:"group_id" json:"group_id"`
	ID         uuid.UUID          `db:"id" json:"id"`
	DisabledAt pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

func (q *Queries) DisableGroupInviteLink(ctx context.Context, arg DisableGroupInviteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableGroupInviteLink, arg.GroupID, arg.ID, arg.DisabledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT EXISTS (
    SELECT 1
    FROM user_friendships
    WHERE user_low_id = $1 AND user_high_id = $2
) AS friendship_exists
`

type FriendshipExistsParams struct {
	UserLowID  uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, arg.UserLowID, arg.UserHighID)
	var friendship_exists bool
	err := row.Scan(&friendship_exists)
	return friendship_exists, err
}

const getDirectChatMessageByID = `-- name: GetDirectChatMessageByID :one
SELECT
    m.id,
    m.chat_id,
    m.sender_user_id,
    m.kind,
    m.text_content,
    m.markdown_policy,
    m.created_at,
    m.updated_at,
    t.deleted_by_user_id,
    t.deleted_at,
    EXISTS (
        SELECT 1
        FROM direct_chat_pins AS p
        WHERE p.chat_id = m.chat_id AND p.message_id = m.id
    ) AS pinned
FROM direct_chat_messages AS m
JOIN direct_chat_participants AS self ON self.chat_id = m.chat_id
LEFT JOIN direct_chat_message_tombstones AS t ON t.message_id = m.id
WHERE self.user_id = $1 AND m.chat_id = $2 AND m.id = $3
`

type GetDirectChatMessageByIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type GetDirectChatMessageByIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID    uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind            string             `db:"kind" json:"kind"`
	TextContent     string             `db:"text_content" json:"text_content"`
	MarkdownPolicy  string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedByUserID pgtype.UUID        `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Pinned          bool               `db:"pinned" json:"pinned"`
}

func (q *Queries) GetDirectChatMessageByID(ctx context.Context, arg GetDirectChatMessageByIDParams) (GetDirectChatMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getDirectChatMessageByID, arg.UserID, arg.ChatID, arg.ID)
	var i GetDirectChatMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderUserID,
		&i.Kind,
		&i.TextContent,
		&i.MarkdownPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.Pinned,
	)
	return i, err
}

const getDirectChatRelationshipState = `-- name: GetDirectChatRelationshipState :one
SELECT
    EXISTS (
        SELECT 1
        FROM user_blocks AS b
        WHERE (b.blocker_user_id = $1 AND b.blocked_user_id = $2)
           OR (b.blocker_user_id = $2 AND b.blocked_user_id = $1)
    ) AS has_block,
    EXISTS (
        SELECT 1
        FROM user_friendships AS f
        WHERE f.user_low_id = $3 AND f.user_high_id = $4
    ) AS are_friends
`

type GetDirectChatRelationshipStateParams struct {
	BlockerUserID uuid.UUID `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID `db:"blocked_user_id" json:"blocked_user_id"`
	UserLowID     uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID    uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

type GetDirectChatRelationshipStateRow struct {
	HasBlock   bool `db:"has_block" json:"has_block"`
	AreFriends bool `db:"are_friends" json:"are_friends"`
}

func (q *Queries) GetDirectChatRelationshipState(ctx context.Context, arg GetDirectChatRelationshipStateParams) (GetDirectChatRelationshipStateRow, error) {
	row := q.db.QueryRow(ctx, getDirectChatRelationshipState,
		arg.BlockerUserID,
		arg.BlockedUserID,
		arg.UserLowID,
		arg.UserHighID,
	)
	var i GetDirectChatRelationshipStateRow
	err := row.Scan(&i.HasBlock, &i.AreFriends)
	return i, err
}

const getDirectChatRowsByIDAndUserID = `-- name: GetDirectChatRowsByIDAndUserID :many
SELECT
    c.id AS chat_id,
    c.created_by_user_id,
    c.user_low_id,
    c.user_high_id,
    c.created_at AS chat_created_at,
    c.updated_at AS chat_updated_at,
    p.user_id AS participant_user_id,
    u.login AS participant_login,
    u.nickname AS participant_nickname,
    u.avatar_url AS participant_avatar_url
FROM direct_chat_participants AS self
JOIN direct_chats AS c ON c.id = self.chat_id
JOIN direct_chat_participants AS p ON p.chat_id = c.id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND c.id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type GetDirectChatRowsByIDAndUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type GetDirectChatRowsByIDAndUserIDRow struct {
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID            uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID           uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	ChatCreatedAt        pgtype.Timestamptz `db:"chat_created_at" json:"chat_created_at"`
	ChatUpdatedAt        pgtype.Timestamptz `db:"chat_updated_at" json:"chat_updated_at"`
	ParticipantUserID    uuid.UUID          `db:"participant_user_id" json:"participant_user_id"`
	ParticipantLogin     string             `db:"participant_login" json:"participant_login"`
	ParticipantNickname  string             `db:"participant_nickname" json:"participant_nickname"`
	ParticipantAvatarUrl pgtype.Text        `db:"participant_avatar_url" json:"participant_avatar_url"`
}

func (q *Queries) GetDirectChatRowsByIDAndUserID(ctx context.Context, arg GetDirectChatRowsByIDAndUserIDParams) ([]GetDirectChatRowsByIDAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, getDirectChatRowsByIDAndUserID, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectChatRowsByIDAndUserIDRow
	for rows.Next() {
		var i GetDirectChatRowsByIDAndUserIDRow
		if err := rows.Scan(
			&i.ChatID,
			&i.CreatedByUserID,
			&i.UserLowID,
			&i.UserHighID,
			&i.ChatCreatedAt,
			&i.ChatUpdatedAt,
			&i.ParticipantUserID,
			&i.ParticipantLogin,
			&i.ParticipantNickname,
			&i.ParticipantAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupChatThreadRowByGroupIDAndUserID = `-- name: GetGroupChatThreadRowByGroupIDAndUserID :one
SELECT
    t.id,
    t.group_id,
    t.thread_key,
    t.created_at,
    t.updated_at
FROM group_memberships AS self
JOIN group_threads AS t ON t.group_id = self.group_id
WHERE self.user_id = $1
  AND self.group_id = $2
  AND t.thread_key = 'primary'
`

type GetGroupChatThreadRowByGroupIDAndUserIDParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) GetGroupChatThreadRowByGroupIDAndUserID(ctx context.Context, arg GetGroupChatThreadRowByGroupIDAndUserIDParams) (GroupThread, error) {
	row := q.db.QueryRow(ctx, getGroupChatThreadRowByGroupIDAndUserID, arg.UserID, arg.GroupID)
	var i GroupThread
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ThreadKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupInviteLinkByIDAndGroupID = `-- name: GetGroupInviteLinkByIDAndGroupID :one
SELECT
    id,
    group_id,
    created_by_user_id,
    role,
    join_count,
    created_at,
    updated_at,
    disabled_at,
    last_joined_at
FROM group_invite_links
WHERE group_id = $1 AND id = $2
`

type GetGroupInviteLinkByIDAndGroupIDParams struct {
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	ID      uuid.UUID `db:"id" json:"id"`
}

type GetGroupInviteLinkByIDAndGroupIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role            string             `db:"role" json:"role"`
	JoinCount       int32              `db:"join_count" json:"join_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastJoinedAt    pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
}

func (q *Queries) GetGroupInviteLinkByIDAndGroupID(ctx context.Context, arg GetGroupInviteLinkByIDAndGroupIDParams) (GetGroupInviteLinkByIDAndGroupIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupInviteLinkByIDAndGroupID, arg.GroupID, arg.ID)
	var i GetGroupInviteLinkByIDAndGroupIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Role,
		&i.JoinCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.LastJoinedAt,
	)
	return i, err
}

const getGroupInviteLinkForJoin = `-- name: GetGroupInviteLinkForJoin :one
SELECT
    l.id,
    l.group_id,
    l.created_by_user_id,
    l.role,
    l.join_count,
    l.created_at,
    l.updated_at,
    l.disabled_at,
    l.last_joined_at,
    g.name AS group_name,
    g.created_by_user_id AS group_created_by_user_id,
    g.created_at AS group_created_at,
    g.updated_at AS group_updated_at
FROM group_invite_links AS l
JOIN groups AS g ON g.id = l.group_id
WHERE l.token_hash = $1
`

type GetGroupInviteLinkForJoinRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	GroupID              uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role                 string             `db:"role" json:"role"`
	JoinCount            int32              `db:"join_count" json:"join_count"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt           pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastJoinedAt         pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
	GroupName            string             `db:"group_name" json:"group_name"`
	GroupCreatedByUserID uuid.UUID          `db:"group_created_by_user_id" json:"group_created_by_user_id"`
	GroupCreatedAt       pgtype.Timestamptz `db:"group_created_at" json:"group_created_at"`
	GroupUpdatedAt       pgtype.Timestamptz `db:"group_updated_at" json:"group_updated_at"`
}

func (q *Queries) GetGroupInviteLinkForJoin(ctx context.Context, tokenHash string) (GetGroupInviteLinkForJoinRow, error) {
	row := q.db.QueryRow(ctx, getGroupInviteLinkForJoin, tokenHash)
	var i GetGroupInviteLinkForJoinRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Role,
		&i.JoinCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.LastJoinedAt,
		&i.GroupName,
		&i.GroupCreatedByUserID,
		&i.GroupCreatedAt,
		&i.GroupUpdatedAt,
	)
	return i, err
}

const getGroupRowByIDAndUserID = `-- name: GetGroupRowByIDAndUserID :one
SELECT
    g.id,
    g.name,
    g.created_by_user_id,
    self.role AS self_role,
    g.created_at,
    g.updated_at,
    COUNT(m.user_id)::INT AS member_count
FROM group_memberships AS self
JOIN groups AS g ON g.id = self.group_id
JOIN group_memberships AS m ON m.group_id = g.id
WHERE self.user_id = $1 AND g.id = $2
GROUP BY g.id, g.name, g.created_by_user_id, self.role, g.created_at, g.updated_at
`

type GetGroupRowByIDAndUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type GetGroupRowByIDAndUserIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	SelfRole        string             `db:"self_role" json:"self_role"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MemberCount     int32              `db:"member_count" json:"member_count"`
}

func (q *Queries) GetGroupRowByIDAndUserID(ctx context.Context, arg GetGroupRowByIDAndUserIDParams) (GetGroupRowByIDAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupRowByIDAndUserID, arg.UserID, arg.ID)
	var i GetGroupRowByIDAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedByUserID,
		&i.SelfRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberCount,
	)
	return i, err
}

const getSessionAuthByID = `-- name: GetSessionAuthByID :one
SELECT
    s.id AS session_id,
    s.user_id AS session_user_id,
    s.device_id AS session_device_id,
    s.token_hash,
    s.created_at AS session_created_at,
    s.last_seen_at AS session_last_seen_at,
    s.revoked_at AS session_revoked_at,
    d.id AS device_id,
    d.user_id AS device_user_id,
    d.label AS device_label,
    d.created_at AS device_created_at,
    d.last_seen_at AS device_last_seen_at,
    d.revoked_at AS device_revoked_at,
    u.id AS user_id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at
FROM user_sessions AS s
JOIN user_devices AS d ON d.id = s.device_id
JOIN users AS u ON u.id = s.user_id
WHERE s.id = $1
`

type GetSessionAuthByIDRow struct {
	SessionID               uuid.UUID          `db:"session_id" json:"session_id"`
	SessionUserID           uuid.UUID          `db:"session_user_id" json:"session_user_id"`
	SessionDeviceID         uuid.UUID          `db:"session_device_id" json:"session_device_id"`
	TokenHash               string             `db:"token_hash" json:"token_hash"`
	SessionCreatedAt        pgtype.Timestamptz `db:"session_created_at" json:"session_created_at"`
	SessionLastSeenAt       pgtype.Timestamptz `db:"session_last_seen_at" json:"session_last_seen_at"`
	SessionRevokedAt        pgtype.Timestamptz `db:"session_revoked_at" json:"session_revoked_at"`
	DeviceID                uuid.UUID          `db:"device_id" json:"device_id"`
	DeviceUserID            uuid.UUID          `db:"device_user_id" json:"device_user_id"`
	DeviceLabel             string             `db:"device_label" json:"device_label"`
	DeviceCreatedAt         pgtype.Timestamptz `db:"device_created_at" json:"device_created_at"`
	DeviceLastSeenAt        pgtype.Timestamptz `db:"device_last_seen_at" json:"device_last_seen_at"`
	DeviceRevokedAt         pgtype.Timestamptz `db:"device_revoked_at" json:"device_revoked_at"`
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Login                   string             `db:"login" json:"login"`
	Nickname                string             `db:"nickname" json:"nickname"`
	AvatarUrl               pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	ReadReceiptsEnabled     bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled         bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	UserCreatedAt           pgtype.Timestamptz `db:"user_created_at" json:"user_created_at"`
	UserUpdatedAt           pgtype.Timestamptz `db:"user_updated_at" json:"user_updated_at"`
}

func (q *Queries) GetSessionAuthByID(ctx context.Context, id uuid.UUID) (GetSessionAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionAuthByID, id)
	var i GetSessionAuthByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionUserID,
		&i.SessionDeviceID,
		&i.TokenHash,
		&i.SessionCreatedAt,
		&i.SessionLastSeenAt,
		&i.SessionRevokedAt,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.DeviceLabel,
		&i.DeviceCreatedAt,
		&i.DeviceLastSeenAt,
		&i.DeviceRevokedAt,
		&i.UserID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const joinGroupMembership = `-- name: JoinGroupMembership :execrows
INSERT INTO group_memberships (
    group_id,
    user_id,
    role,
    joined_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type JoinGroupMembershipParams struct {
	GroupID  uuid.UUID          `db:"group_id" json:"group_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) JoinGroupMembership(ctx context.Context, arg JoinGroupMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, joinGroupMembership,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDirectChatMessages = `-- name: ListDirectChatMessages :many
SELECT
    m.id,
    m.chat_id,
    m.sender_user_id,
    m.kind,
    m.text_content,
    m.markdown_policy,
    m.created_at,
    m.updated_at,
    t.deleted_by_user_id,
    t.deleted_at,
    EXISTS (
        SELECT 1
        FROM direct_chat_pins AS p
        WHERE p.chat_id = m.chat_id AND p.message_id = m.id
    ) AS pinned
FROM direct_chat_messages AS m
JOIN direct_chat_participants AS self ON self.chat_id = m.chat_id
LEFT JOIN direct_chat_message_tombstones AS t ON t.message_id = m.id
WHERE self.user_id = $1 AND m.chat_id = $2
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListDirectChatMessagesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
	Limit  int32     `db:"limit" json:"limit"`
}

type ListDirectChatMessagesRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID    uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind            string             `db:"kind" json:"kind"`
	TextContent     string             `db:"text_content" json:"text_content"`
	MarkdownPolicy  string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedByUserID pgtype.UUID        `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Pinned          bool               `db:"pinned" json:"pinned"`
}

func (q *Queries) ListDirectChatMessages(ctx context.Context, arg ListDirectChatMessagesParams) ([]ListDirectChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatMessages, arg.UserID, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatMessagesRow
	for rows.Next() {
		var i ListDirectChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderUserID,
			&i.Kind,
			&i.TextContent,
			&i.MarkdownPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedByUserID,
			&i.DeletedAt,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatPresenceStateEntries = `-- name: ListDirectChatPresenceStateEntries :many
SELECT
    p.user_id,
    u.presence_enabled
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatPresenceStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatPresenceStateEntriesRow struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	PresenceEnabled bool      `db:"presence_enabled" json:"presence_enabled"`
}

func (q *Queries) ListDirectChatPresenceStateEntries(ctx context.Context, arg ListDirectChatPresenceStateEntriesParams) ([]ListDirectChatPresenceStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatPresenceStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatPresenceStateEntriesRow
	for rows.Next() {
		var i ListDirectChatPresenceStateEntriesRow
		if err := rows.Scan(&i.UserID, &i.PresenceEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatReadStateEntries = `-- name: ListDirectChatReadStateEntries :many
SELECT
    p.user_id,
    u.read_receipts_enabled,
    r.last_read_message_id,
    r.last_read_message_created_at,
    r.updated_at
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
LEFT JOIN direct_chat_read_receipts AS r ON r.chat_id = p.chat_id AND r.user_id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatReadStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatReadStateEntriesRow struct {
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	LastReadMessageID        pgtype.UUID        `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListDirectChatReadStateEntries(ctx context.Context, arg ListDirectChatReadStateEntriesParams) ([]ListDirectChatReadStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatReadStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatReadStateEntriesRow
	for rows.Next() {
		var i ListDirectChatReadStateEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ReadReceiptsEnabled,
			&i.LastReadMessageID,
			&i.LastReadMessageCreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatRowsByUserID = `-- name: ListDirectChatRowsByUserID :many
SELECT
    c.id AS chat_id,
    c.created_by_user_id,
    c.user_low_id,
    c.user_high_id,
    c.created_at AS chat_created_at,
    c.updated_at AS chat_updated_at,
    p.user_id AS participant_user_id,
    u.login AS participant_login,
    u.nickname AS participant_nickname,
    u.avatar_url AS participant_avatar_url
FROM direct_chat_participants AS self
JOIN direct_chats AS c ON c.id = self.chat_id
JOIN direct_chat_participants AS p ON p.chat_id = c.id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1
ORDER BY c.updated_at DESC, c.id DESC, p.joined_at ASC, p.user_id ASC
`

type ListDirectChatRowsByUserIDRow struct {
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID            uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID           uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	ChatCreatedAt        pgtype.Timestamptz `db:"chat_created_at" json:"chat_created_at"`
	ChatUpdatedAt        pgtype.Timestamptz `db:"chat_updated_at" json:"chat_updated_at"`
	ParticipantUserID    uuid.UUID          `db:"participant_user_id" json:"participant_user_id"`
	ParticipantLogin     string             `db:"participant_login" json:"participant_login"`
	ParticipantNickname  string             `db:"participant_nickname" json:"participant_nickname"`
	ParticipantAvatarUrl pgtype.Text        `db:"participant_avatar_url" json:"participant_avatar_url"`
}

func (q *Queries) ListDirectChatRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListDirectChatRowsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatRowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatRowsByUserIDRow
	for rows.Next() {
		var i ListDirectChatRowsByUserIDRow
		if err := rows.Scan(
			&i.ChatID,
			&i.CreatedByUserID,
			&i.UserLowID,
			&i.UserHighID,
			&i.ChatCreatedAt,
			&i.ChatUpdatedAt,
			&i.ParticipantUserID,
			&i.ParticipantLogin,
			&i.ParticipantNickname,
			&i.ParticipantAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatTypingStateEntries = `-- name: ListDirectChatTypingStateEntries :many
SELECT
    p.user_id,
    u.typing_visibility_enabled
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatTypingStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatTypingStateEntriesRow struct {
	UserID                  uuid.UUID `db:"user_id" json:"user_id"`
	TypingVisibilityEnabled bool      `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
}

func (q *Queries) ListDirectChatTypingStateEntries(ctx context.Context, arg ListDirectChatTypingStateEntriesParams) ([]ListDirectChatTypingStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatTypingStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatTypingStateEntriesRow
	for rows.Next() {
		var i ListDirectChatTypingStateEntriesRow
		if err := rows.Scan(&i.UserID, &i.TypingVisibilityEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupInviteLinksByGroupID = `-- name: ListGroupInviteLinksByGroupID :many
SELECT
    id,
    group_id,
    created_by_user_id,
    role,
    join_count,
    created_at,
    updated_at,
    disabled_at,
    last_joined_at
FROM group_invite_links
WHERE group_id = $1
ORDER BY created_at DESC, id DESC
`

type ListGroupInviteLinksByGroupIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role            string             `db:"role" json:"role"`
	JoinCount       int32              `db:"join_count" json:"join_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastJoinedAt    pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
}

func (q *Queries) ListGroupInviteLinksByGroupID(ctx context.Context, groupID uuid.UUID) ([]ListGroupInviteLinksByGroupIDRow, error) {
	rows, err := q.db.Query(ctx, listGroupInviteLinksByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupInviteLinksByGroupIDRow
	for rows.Next() {
		var i ListGroupInviteLinksByGroupIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedByUserID,
			&i.Role,
			&i.JoinCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
			&i.LastJoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMemberRowsByGroupIDAndUserID = `-- name: ListGroupMemberRowsByGroupIDAndUserID :many
SELECT
    m.group_id,
    m.user_id,
    m.role,
    m.joined_at,
    u.login,
    u.nickname,
    u.avatar_url
FROM group_memberships AS self
JOIN group_memberships AS m ON m.group_id = self.group_id
JOIN users AS u ON u.id = m.user_id
WHERE self.user_id = $1 AND self.group_id = $2
ORDER BY
    CASE m.role
        WHEN 'owner' THEN 0
        WHEN 'admin' THEN 1
        WHEN 'member' THEN 2
        WHEN 'reader' THEN 3
        ELSE 4
    END,
    m.joined_at ASC,
    m.user_id ASC
`

type ListGroupMemberRowsByGroupIDAndUserIDParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

type ListGroupMemberRowsByGroupIDAndUserIDRow struct {
	GroupID   uuid.UUID          `db:"group_id" json:"group_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Role      string             `db:"role" json:"role"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	Login     string             `db:"login" json:"login"`
	Nickname  string             `db:"nickname" json:"nickname"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListGroupMemberRowsByGroupIDAndUserID(ctx context.Context, arg ListGroupMemberRowsByGroupIDAndUserIDParams) ([]ListGroupMemberRowsByGroupIDAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, listGroupMemberRowsByGroupIDAndUserID, arg.UserID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMemberRowsByGroupIDAndUserIDRow
	for rows.Next() {
		var i ListGroupMemberRowsByGroupIDAndUserIDRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Login,
			&i.Nickname,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMessagesByGroupIDAndUserID = `-- name: ListGroupMessagesByGroupIDAndUserID :many
SELECT
    m.id,
    t.group_id,
    m.thread_id,
    m.sender_user_id,
    m.kind,
    m.text_content,
    m.markdown_policy,
    m.created_at,
    m.updated_at
FROM group_memberships AS self
JOIN group_threads AS t ON t.group_id = self.group_id
JOIN group_messages AS m ON m.thread_id = t.id
WHERE self.user_id = $1
  AND self.group_id = $2
  AND t.thread_key = 'primary'
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListGroupMessagesByGroupIDAndUserIDParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
	Limit   int32     `db:"limit" json:"limit"`
}

type ListGroupMessagesByGroupIDAndUserIDRow struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	GroupID        uuid.UUID          `db:"group_id" json:"group_id"`
	ThreadID       uuid.UUID          `db:"thread_id" json:"thread_id"`
	SenderUserID   uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind           string             `db:"kind" json:"kind"`
	TextContent    string             `db:"text_content" json:"text_content"`
	MarkdownPolicy string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListGroupMessagesByGroupIDAndUserID(ctx context.Context, arg ListGroupMessagesByGroupIDAndUserIDParams) ([]ListGroupMessagesByGroupIDAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, listGroupMessagesByGroupIDAndUserID, arg.UserID, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMessagesByGroupIDAndUserIDRow
	for rows.Next() {
		var i ListGroupMessagesByGroupIDAndUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ThreadID,
			&i.SenderUserID,
			&i.Kind,
			&i.TextContent,
			&i.MarkdownPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupRowsByUserID = `-- name: ListGroupRowsByUserID :many
SELECT
    g.id,
    g.name,
    g.created_by_user_id,
    self.role AS self_role,
    g.created_at,
    g.updated_at,
    COUNT(m.user_id)::INT AS member_count
FROM group_memberships AS self
JOIN groups AS g ON g.id = self.group_id
JOIN group_memberships AS m ON m.group_id = g.id
WHERE self.user_id = $1
GROUP BY g.id, g.name, g.created_by_user_id, self.role, g.created_at, g.updated_at
ORDER BY g.updated_at DESC, g.id DESC
`

type ListGroupRowsByUserIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	SelfRole        string             `db:"self_role" json:"self_role"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	MemberCount     int32              `db:"member_count" json:"member_count"`
}

func (q *Queries) ListGroupRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListGroupRowsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listGroupRowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupRowsByUserIDRow
	for rows.Next() {
		var i ListGroupRowsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedByUserID,
			&i.SelfRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessageIDsByChatID = `-- name: ListPinnedMessageIDsByChatID :many
SELECT message_id
FROM direct_chat_pins
WHERE chat_id = $1
ORDER BY created_at DESC, message_id DESC
`

func (q *Queries) ListPinnedMessageIDsByChatID(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPinnedMessageIDsByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var message_id uuid.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinDirectChatMessage = `-- name: PinDirectChatMessage :execrows
INSERT INTO direct_chat_pins (
    chat_id,
    message_id,
    pinned_by_user_id,
    created_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (chat_id, message_id) DO NOTHING
`

type PinDirectChatMessageParams struct {
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) PinDirectChatMessage(ctx context.Context, arg PinDirectChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinDirectChatMessage,
		arg.ChatID,
		arg.MessageID,
		arg.PinnedByUserID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDirectChatMessageUpdatedAt = `-- name: TouchDirectChatMessageUpdatedAt :exec
UPDATE direct_chat_messages
SET updated_at = $2
WHERE id = $1
`

type TouchDirectChatMessageUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchDirectChatMessageUpdatedAt(ctx context.Context, arg TouchDirectChatMessageUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchDirectChatMessageUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchDirectChatUpdatedAt = `-- name: TouchDirectChatUpdatedAt :exec
UPDATE direct_chats
SET updated_at = $2
WHERE id = $1
`

type TouchDirectChatUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchDirectChatUpdatedAt(ctx context.Context, arg TouchDirectChatUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchDirectChatUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchGroupInviteLinkJoin = `-- name: TouchGroupInviteLinkJoin :exec
UPDATE group_invite_links
SET
    join_count = join_count + 1,
    last_joined_at = $2,
    updated_at = $2
WHERE id = $1
`

type TouchGroupInviteLinkJoinParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	LastJoinedAt pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
}

func (q *Queries) TouchGroupInviteLinkJoin(ctx context.Context, arg TouchGroupInviteLinkJoinParams) error {
	_, err := q.db.Exec(ctx, touchGroupInviteLinkJoin, arg.ID, arg.LastJoinedAt)
	return err
}

const touchGroupThreadUpdatedAt = `-- name: TouchGroupThreadUpdatedAt :exec
UPDATE group_threads
SET updated_at = $2
WHERE id = $1
`

type TouchGroupThreadUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchGroupThreadUpdatedAt(ctx context.Context, arg TouchGroupThreadUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchGroupThreadUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchGroupUpdatedAt = `-- name: TouchGroupUpdatedAt :exec
UPDATE groups
SET updated_at = $2
WHERE id = $1
`

type TouchGroupUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchGroupUpdatedAt(ctx context.Context, arg TouchGroupUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchGroupUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchSessionAndDevice = `-- name: TouchSessionAndDevice :exec
WITH touched_session AS (
    UPDATE user_sessions AS s
    SET last_seen_at = $3
    WHERE s.id = $1 AND s.device_id = $2
), touched_device AS (
    UPDATE user_devices AS d
    SET last_seen_at = $3
    WHERE d.id = $2
)
SELECT 1
`

type TouchSessionAndDeviceParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) TouchSessionAndDevice(ctx context.Context, arg TouchSessionAndDeviceParams) error {
	_, err := q.db.Exec(ctx, touchSessionAndDevice, arg.ID, arg.DeviceID, arg.LastSeenAt)
	return err
}

const unpinDirectChatMessage = `-- name: UnpinDirectChatMessage :execrows
DELETE FROM direct_chat_pins
WHERE chat_id = $1 AND message_id = $2
`

type UnpinDirectChatMessageParams struct {
	ChatID    uuid.UUID `db:"chat_id" json:"chat_id"`
	MessageID uuid.UUID `db:"message_id" json:"message_id"`
}

func (q *Queries) UnpinDirectChatMessage(ctx context.Context, arg UnpinDirectChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpinDirectChatMessage, arg.ChatID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDirectChatReadReceipt = `-- name: UpsertDirectChatReadReceipt :execrows
INSERT INTO direct_chat_read_receipts (
    chat_id,
    user_id,
    last_read_message_id,
    last_read_message_created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chat_id, user_id) DO UPDATE
SET
    last_read_message_id = EXCLUDED.last_read_message_id,
    last_read_message_created_at = EXCLUDED.last_read_message_created_at,
    updated_at = EXCLUDED.updated_at
WHERE direct_chat_read_receipts.last_read_message_created_at < EXCLUDED.last_read_message_created_at
   OR (
        direct_chat_read_receipts.last_read_message_created_at = EXCLUDED.last_read_message_created_at
        AND direct_chat_read_receipts.last_read_message_id < EXCLUDED.last_read_message_id
   )
`

type UpsertDirectChatReadReceiptParams struct {
	ChatID                   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertDirectChatReadReceipt(ctx context.Context, arg UpsertDirectChatReadReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDirectChatReadReceipt,
		arg.ChatID,
		arg.UserID,
		arg.LastReadMessageID,
		arg.LastReadMessageCreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
