// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package chatsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDirectChatParticipant = `-- name: AddDirectChatParticipant :exec
INSERT INTO direct_chat_participants (
    chat_id,
    user_id,
    joined_at
) VALUES ($1, $2, $3)
`

type AddDirectChatParticipantParams struct {
	ChatID   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

func (q *Queries) AddDirectChatParticipant(ctx context.Context, arg AddDirectChatParticipantParams) error {
	_, err := q.db.Exec(ctx, addDirectChatParticipant, arg.ChatID, arg.UserID, arg.JoinedAt)
	return err
}

const createDirectChat = `-- name: CreateDirectChat :one
INSERT INTO direct_chats (
    id,
    created_by_user_id,
    user_low_id,
    user_high_id,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_by_user_id, user_low_id, user_high_id, created_at, updated_at
`

type CreateDirectChatParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDirectChat(ctx context.Context, arg CreateDirectChatParams) (DirectChat, error) {
	row := q.db.QueryRow(ctx, createDirectChat,
		arg.ID,
		arg.CreatedByUserID,
		arg.UserLowID,
		arg.UserHighID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DirectChat
	err := row.Scan(
		&i.ID,
		&i.CreatedByUserID,
		&i.UserLowID,
		&i.UserHighID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectChatMessage = `-- name: CreateDirectChatMessage :one
INSERT INTO direct_chat_messages (
    id,
    chat_id,
    sender_user_id,
    kind,
    text_content,
    markdown_policy,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, chat_id, sender_user_id, kind, text_content, markdown_policy, created_at, updated_at
`

type CreateDirectChatMessageParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID   uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind           string             `db:"kind" json:"kind"`
	TextContent    string             `db:"text_content" json:"text_content"`
	MarkdownPolicy string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateDirectChatMessage(ctx context.Context, arg CreateDirectChatMessageParams) (DirectChatMessage, error) {
	row := q.db.QueryRow(ctx, createDirectChatMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderUserID,
		arg.Kind,
		arg.TextContent,
		arg.MarkdownPolicy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DirectChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderUserID,
		&i.Kind,
		&i.TextContent,
		&i.MarkdownPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectChatMessageTombstone = `-- name: CreateDirectChatMessageTombstone :execrows
INSERT INTO direct_chat_message_tombstones (
    message_id,
    chat_id,
    deleted_by_user_id,
    deleted_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id) DO NOTHING
`

type CreateDirectChatMessageTombstoneParams struct {
	MessageID       uuid.UUID          `db:"message_id" json:"message_id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	DeletedByUserID uuid.UUID          `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

func (q *Queries) CreateDirectChatMessageTombstone(ctx context.Context, arg CreateDirectChatMessageTombstoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, createDirectChatMessageTombstone,
		arg.MessageID,
		arg.ChatID,
		arg.DeletedByUserID,
		arg.DeletedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const friendshipExists = `-- name: FriendshipExists :one
SELECT EXISTS (
    SELECT 1
    FROM user_friendships
    WHERE user_low_id = $1 AND user_high_id = $2
) AS friendship_exists
`

type FriendshipExistsParams struct {
	UserLowID  uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

func (q *Queries) FriendshipExists(ctx context.Context, arg FriendshipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, friendshipExists, arg.UserLowID, arg.UserHighID)
	var friendship_exists bool
	err := row.Scan(&friendship_exists)
	return friendship_exists, err
}

const getDirectChatMessageByID = `-- name: GetDirectChatMessageByID :one
SELECT
    m.id,
    m.chat_id,
    m.sender_user_id,
    m.kind,
    m.text_content,
    m.markdown_policy,
    m.created_at,
    m.updated_at,
    t.deleted_by_user_id,
    t.deleted_at,
    EXISTS (
        SELECT 1
        FROM direct_chat_pins AS p
        WHERE p.chat_id = m.chat_id AND p.message_id = m.id
    ) AS pinned
FROM direct_chat_messages AS m
JOIN direct_chat_participants AS self ON self.chat_id = m.chat_id
LEFT JOIN direct_chat_message_tombstones AS t ON t.message_id = m.id
WHERE self.user_id = $1 AND m.chat_id = $2 AND m.id = $3
`

type GetDirectChatMessageByIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type GetDirectChatMessageByIDRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID    uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind            string             `db:"kind" json:"kind"`
	TextContent     string             `db:"text_content" json:"text_content"`
	MarkdownPolicy  string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedByUserID pgtype.UUID        `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Pinned          bool               `db:"pinned" json:"pinned"`
}

func (q *Queries) GetDirectChatMessageByID(ctx context.Context, arg GetDirectChatMessageByIDParams) (GetDirectChatMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getDirectChatMessageByID, arg.UserID, arg.ChatID, arg.ID)
	var i GetDirectChatMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderUserID,
		&i.Kind,
		&i.TextContent,
		&i.MarkdownPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedByUserID,
		&i.DeletedAt,
		&i.Pinned,
	)
	return i, err
}

const getDirectChatRelationshipState = `-- name: GetDirectChatRelationshipState :one
SELECT
    EXISTS (
        SELECT 1
        FROM user_blocks AS b
        WHERE (b.blocker_user_id = $1 AND b.blocked_user_id = $2)
           OR (b.blocker_user_id = $2 AND b.blocked_user_id = $1)
    ) AS has_block,
    EXISTS (
        SELECT 1
        FROM user_friendships AS f
        WHERE f.user_low_id = $3 AND f.user_high_id = $4
    ) AS are_friends
`

type GetDirectChatRelationshipStateParams struct {
	BlockerUserID uuid.UUID `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID `db:"blocked_user_id" json:"blocked_user_id"`
	UserLowID     uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID    uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

type GetDirectChatRelationshipStateRow struct {
	HasBlock   bool `db:"has_block" json:"has_block"`
	AreFriends bool `db:"are_friends" json:"are_friends"`
}

func (q *Queries) GetDirectChatRelationshipState(ctx context.Context, arg GetDirectChatRelationshipStateParams) (GetDirectChatRelationshipStateRow, error) {
	row := q.db.QueryRow(ctx, getDirectChatRelationshipState,
		arg.BlockerUserID,
		arg.BlockedUserID,
		arg.UserLowID,
		arg.UserHighID,
	)
	var i GetDirectChatRelationshipStateRow
	err := row.Scan(&i.HasBlock, &i.AreFriends)
	return i, err
}

const getDirectChatRowsByIDAndUserID = `-- name: GetDirectChatRowsByIDAndUserID :many
SELECT
    c.id AS chat_id,
    c.created_by_user_id,
    c.user_low_id,
    c.user_high_id,
    c.created_at AS chat_created_at,
    c.updated_at AS chat_updated_at,
    p.user_id AS participant_user_id,
    u.login AS participant_login,
    u.nickname AS participant_nickname,
    u.avatar_url AS participant_avatar_url
FROM direct_chat_participants AS self
JOIN direct_chats AS c ON c.id = self.chat_id
JOIN direct_chat_participants AS p ON p.chat_id = c.id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND c.id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type GetDirectChatRowsByIDAndUserIDParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ID     uuid.UUID `db:"id" json:"id"`
}

type GetDirectChatRowsByIDAndUserIDRow struct {
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID            uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID           uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	ChatCreatedAt        pgtype.Timestamptz `db:"chat_created_at" json:"chat_created_at"`
	ChatUpdatedAt        pgtype.Timestamptz `db:"chat_updated_at" json:"chat_updated_at"`
	ParticipantUserID    uuid.UUID          `db:"participant_user_id" json:"participant_user_id"`
	ParticipantLogin     string             `db:"participant_login" json:"participant_login"`
	ParticipantNickname  string             `db:"participant_nickname" json:"participant_nickname"`
	ParticipantAvatarUrl pgtype.Text        `db:"participant_avatar_url" json:"participant_avatar_url"`
}

func (q *Queries) GetDirectChatRowsByIDAndUserID(ctx context.Context, arg GetDirectChatRowsByIDAndUserIDParams) ([]GetDirectChatRowsByIDAndUserIDRow, error) {
	rows, err := q.db.Query(ctx, getDirectChatRowsByIDAndUserID, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectChatRowsByIDAndUserIDRow
	for rows.Next() {
		var i GetDirectChatRowsByIDAndUserIDRow
		if err := rows.Scan(
			&i.ChatID,
			&i.CreatedByUserID,
			&i.UserLowID,
			&i.UserHighID,
			&i.ChatCreatedAt,
			&i.ChatUpdatedAt,
			&i.ParticipantUserID,
			&i.ParticipantLogin,
			&i.ParticipantNickname,
			&i.ParticipantAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionAuthByID = `-- name: GetSessionAuthByID :one
SELECT
    s.id AS session_id,
    s.user_id AS session_user_id,
    s.device_id AS session_device_id,
    s.token_hash,
    s.created_at AS session_created_at,
    s.last_seen_at AS session_last_seen_at,
    s.revoked_at AS session_revoked_at,
    d.id AS device_id,
    d.user_id AS device_user_id,
    d.label AS device_label,
    d.created_at AS device_created_at,
    d.last_seen_at AS device_last_seen_at,
    d.revoked_at AS device_revoked_at,
    u.id AS user_id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at
FROM user_sessions AS s
JOIN user_devices AS d ON d.id = s.device_id
JOIN users AS u ON u.id = s.user_id
WHERE s.id = $1
`

type GetSessionAuthByIDRow struct {
	SessionID               uuid.UUID          `db:"session_id" json:"session_id"`
	SessionUserID           uuid.UUID          `db:"session_user_id" json:"session_user_id"`
	SessionDeviceID         uuid.UUID          `db:"session_device_id" json:"session_device_id"`
	TokenHash               string             `db:"token_hash" json:"token_hash"`
	SessionCreatedAt        pgtype.Timestamptz `db:"session_created_at" json:"session_created_at"`
	SessionLastSeenAt       pgtype.Timestamptz `db:"session_last_seen_at" json:"session_last_seen_at"`
	SessionRevokedAt        pgtype.Timestamptz `db:"session_revoked_at" json:"session_revoked_at"`
	DeviceID                uuid.UUID          `db:"device_id" json:"device_id"`
	DeviceUserID            uuid.UUID          `db:"device_user_id" json:"device_user_id"`
	DeviceLabel             string             `db:"device_label" json:"device_label"`
	DeviceCreatedAt         pgtype.Timestamptz `db:"device_created_at" json:"device_created_at"`
	DeviceLastSeenAt        pgtype.Timestamptz `db:"device_last_seen_at" json:"device_last_seen_at"`
	DeviceRevokedAt         pgtype.Timestamptz `db:"device_revoked_at" json:"device_revoked_at"`
	UserID                  uuid.UUID          `db:"user_id" json:"user_id"`
	Login                   string             `db:"login" json:"login"`
	Nickname                string             `db:"nickname" json:"nickname"`
	AvatarUrl               pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	ReadReceiptsEnabled     bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled         bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	UserCreatedAt           pgtype.Timestamptz `db:"user_created_at" json:"user_created_at"`
	UserUpdatedAt           pgtype.Timestamptz `db:"user_updated_at" json:"user_updated_at"`
}

func (q *Queries) GetSessionAuthByID(ctx context.Context, id uuid.UUID) (GetSessionAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionAuthByID, id)
	var i GetSessionAuthByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionUserID,
		&i.SessionDeviceID,
		&i.TokenHash,
		&i.SessionCreatedAt,
		&i.SessionLastSeenAt,
		&i.SessionRevokedAt,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.DeviceLabel,
		&i.DeviceCreatedAt,
		&i.DeviceLastSeenAt,
		&i.DeviceRevokedAt,
		&i.UserID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const listDirectChatMessages = `-- name: ListDirectChatMessages :many
SELECT
    m.id,
    m.chat_id,
    m.sender_user_id,
    m.kind,
    m.text_content,
    m.markdown_policy,
    m.created_at,
    m.updated_at,
    t.deleted_by_user_id,
    t.deleted_at,
    EXISTS (
        SELECT 1
        FROM direct_chat_pins AS p
        WHERE p.chat_id = m.chat_id AND p.message_id = m.id
    ) AS pinned
FROM direct_chat_messages AS m
JOIN direct_chat_participants AS self ON self.chat_id = m.chat_id
LEFT JOIN direct_chat_message_tombstones AS t ON t.message_id = m.id
WHERE self.user_id = $1 AND m.chat_id = $2
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3
`

type ListDirectChatMessagesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
	Limit  int32     `db:"limit" json:"limit"`
}

type ListDirectChatMessagesRow struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID    uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind            string             `db:"kind" json:"kind"`
	TextContent     string             `db:"text_content" json:"text_content"`
	MarkdownPolicy  string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedByUserID pgtype.UUID        `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	Pinned          bool               `db:"pinned" json:"pinned"`
}

func (q *Queries) ListDirectChatMessages(ctx context.Context, arg ListDirectChatMessagesParams) ([]ListDirectChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatMessages, arg.UserID, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatMessagesRow
	for rows.Next() {
		var i ListDirectChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderUserID,
			&i.Kind,
			&i.TextContent,
			&i.MarkdownPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedByUserID,
			&i.DeletedAt,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatPresenceStateEntries = `-- name: ListDirectChatPresenceStateEntries :many
SELECT
    p.user_id,
    u.presence_enabled
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatPresenceStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatPresenceStateEntriesRow struct {
	UserID          uuid.UUID `db:"user_id" json:"user_id"`
	PresenceEnabled bool      `db:"presence_enabled" json:"presence_enabled"`
}

func (q *Queries) ListDirectChatPresenceStateEntries(ctx context.Context, arg ListDirectChatPresenceStateEntriesParams) ([]ListDirectChatPresenceStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatPresenceStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatPresenceStateEntriesRow
	for rows.Next() {
		var i ListDirectChatPresenceStateEntriesRow
		if err := rows.Scan(&i.UserID, &i.PresenceEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatReadStateEntries = `-- name: ListDirectChatReadStateEntries :many
SELECT
    p.user_id,
    u.read_receipts_enabled,
    r.last_read_message_id,
    r.last_read_message_created_at,
    r.updated_at
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
LEFT JOIN direct_chat_read_receipts AS r ON r.chat_id = p.chat_id AND r.user_id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatReadStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatReadStateEntriesRow struct {
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	LastReadMessageID        pgtype.UUID        `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListDirectChatReadStateEntries(ctx context.Context, arg ListDirectChatReadStateEntriesParams) ([]ListDirectChatReadStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatReadStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatReadStateEntriesRow
	for rows.Next() {
		var i ListDirectChatReadStateEntriesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ReadReceiptsEnabled,
			&i.LastReadMessageID,
			&i.LastReadMessageCreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatRowsByUserID = `-- name: ListDirectChatRowsByUserID :many
SELECT
    c.id AS chat_id,
    c.created_by_user_id,
    c.user_low_id,
    c.user_high_id,
    c.created_at AS chat_created_at,
    c.updated_at AS chat_updated_at,
    p.user_id AS participant_user_id,
    u.login AS participant_login,
    u.nickname AS participant_nickname,
    u.avatar_url AS participant_avatar_url
FROM direct_chat_participants AS self
JOIN direct_chats AS c ON c.id = self.chat_id
JOIN direct_chat_participants AS p ON p.chat_id = c.id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1
ORDER BY c.updated_at DESC, c.id DESC, p.joined_at ASC, p.user_id ASC
`

type ListDirectChatRowsByUserIDRow struct {
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID            uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID           uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	ChatCreatedAt        pgtype.Timestamptz `db:"chat_created_at" json:"chat_created_at"`
	ChatUpdatedAt        pgtype.Timestamptz `db:"chat_updated_at" json:"chat_updated_at"`
	ParticipantUserID    uuid.UUID          `db:"participant_user_id" json:"participant_user_id"`
	ParticipantLogin     string             `db:"participant_login" json:"participant_login"`
	ParticipantNickname  string             `db:"participant_nickname" json:"participant_nickname"`
	ParticipantAvatarUrl pgtype.Text        `db:"participant_avatar_url" json:"participant_avatar_url"`
}

func (q *Queries) ListDirectChatRowsByUserID(ctx context.Context, userID uuid.UUID) ([]ListDirectChatRowsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatRowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatRowsByUserIDRow
	for rows.Next() {
		var i ListDirectChatRowsByUserIDRow
		if err := rows.Scan(
			&i.ChatID,
			&i.CreatedByUserID,
			&i.UserLowID,
			&i.UserHighID,
			&i.ChatCreatedAt,
			&i.ChatUpdatedAt,
			&i.ParticipantUserID,
			&i.ParticipantLogin,
			&i.ParticipantNickname,
			&i.ParticipantAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectChatTypingStateEntries = `-- name: ListDirectChatTypingStateEntries :many
SELECT
    p.user_id,
    u.typing_visibility_enabled
FROM direct_chat_participants AS self
JOIN direct_chat_participants AS p ON p.chat_id = self.chat_id
JOIN users AS u ON u.id = p.user_id
WHERE self.user_id = $1 AND self.chat_id = $2
ORDER BY p.joined_at ASC, p.user_id ASC
`

type ListDirectChatTypingStateEntriesParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	ChatID uuid.UUID `db:"chat_id" json:"chat_id"`
}

type ListDirectChatTypingStateEntriesRow struct {
	UserID                  uuid.UUID `db:"user_id" json:"user_id"`
	TypingVisibilityEnabled bool      `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
}

func (q *Queries) ListDirectChatTypingStateEntries(ctx context.Context, arg ListDirectChatTypingStateEntriesParams) ([]ListDirectChatTypingStateEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChatTypingStateEntries, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChatTypingStateEntriesRow
	for rows.Next() {
		var i ListDirectChatTypingStateEntriesRow
		if err := rows.Scan(&i.UserID, &i.TypingVisibilityEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessageIDsByChatID = `-- name: ListPinnedMessageIDsByChatID :many
SELECT message_id
FROM direct_chat_pins
WHERE chat_id = $1
ORDER BY created_at DESC, message_id DESC
`

func (q *Queries) ListPinnedMessageIDsByChatID(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPinnedMessageIDsByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var message_id uuid.UUID
		if err := rows.Scan(&message_id); err != nil {
			return nil, err
		}
		items = append(items, message_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinDirectChatMessage = `-- name: PinDirectChatMessage :execrows
INSERT INTO direct_chat_pins (
    chat_id,
    message_id,
    pinned_by_user_id,
    created_at
) VALUES ($1, $2, $3, $4)
ON CONFLICT (chat_id, message_id) DO NOTHING
`

type PinDirectChatMessageParams struct {
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) PinDirectChatMessage(ctx context.Context, arg PinDirectChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinDirectChatMessage,
		arg.ChatID,
		arg.MessageID,
		arg.PinnedByUserID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchDirectChatMessageUpdatedAt = `-- name: TouchDirectChatMessageUpdatedAt :exec
UPDATE direct_chat_messages
SET updated_at = $2
WHERE id = $1
`

type TouchDirectChatMessageUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchDirectChatMessageUpdatedAt(ctx context.Context, arg TouchDirectChatMessageUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchDirectChatMessageUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchDirectChatUpdatedAt = `-- name: TouchDirectChatUpdatedAt :exec
UPDATE direct_chats
SET updated_at = $2
WHERE id = $1
`

type TouchDirectChatUpdatedAtParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TouchDirectChatUpdatedAt(ctx context.Context, arg TouchDirectChatUpdatedAtParams) error {
	_, err := q.db.Exec(ctx, touchDirectChatUpdatedAt, arg.ID, arg.UpdatedAt)
	return err
}

const touchSessionAndDevice = `-- name: TouchSessionAndDevice :exec
WITH touched_session AS (
    UPDATE user_sessions AS s
    SET last_seen_at = $3
    WHERE s.id = $1 AND s.device_id = $2
), touched_device AS (
    UPDATE user_devices AS d
    SET last_seen_at = $3
    WHERE d.id = $2
)
SELECT 1
`

type TouchSessionAndDeviceParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) TouchSessionAndDevice(ctx context.Context, arg TouchSessionAndDeviceParams) error {
	_, err := q.db.Exec(ctx, touchSessionAndDevice, arg.ID, arg.DeviceID, arg.LastSeenAt)
	return err
}

const unpinDirectChatMessage = `-- name: UnpinDirectChatMessage :execrows
DELETE FROM direct_chat_pins
WHERE chat_id = $1 AND message_id = $2
`

type UnpinDirectChatMessageParams struct {
	ChatID    uuid.UUID `db:"chat_id" json:"chat_id"`
	MessageID uuid.UUID `db:"message_id" json:"message_id"`
}

func (q *Queries) UnpinDirectChatMessage(ctx context.Context, arg UnpinDirectChatMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpinDirectChatMessage, arg.ChatID, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDirectChatReadReceipt = `-- name: UpsertDirectChatReadReceipt :execrows
INSERT INTO direct_chat_read_receipts (
    chat_id,
    user_id,
    last_read_message_id,
    last_read_message_created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chat_id, user_id) DO UPDATE
SET
    last_read_message_id = EXCLUDED.last_read_message_id,
    last_read_message_created_at = EXCLUDED.last_read_message_created_at,
    updated_at = EXCLUDED.updated_at
WHERE direct_chat_read_receipts.last_read_message_created_at < EXCLUDED.last_read_message_created_at
   OR (
        direct_chat_read_receipts.last_read_message_created_at = EXCLUDED.last_read_message_created_at
        AND direct_chat_read_receipts.last_read_message_id < EXCLUDED.last_read_message_id
   )
`

type UpsertDirectChatReadReceiptParams struct {
	ChatID                   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertDirectChatReadReceipt(ctx context.Context, arg UpsertDirectChatReadReceiptParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDirectChatReadReceipt,
		arg.ChatID,
		arg.UserID,
		arg.LastReadMessageID,
		arg.LastReadMessageCreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
