// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package rtcsqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	OwnerUserID  uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	ScopeKind    string             `db:"scope_kind" json:"scope_kind"`
	DirectChatID pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	BucketName   string             `db:"bucket_name" json:"bucket_name"`
	ObjectKey    string             `db:"object_key" json:"object_key"`
	FileName     string             `db:"file_name" json:"file_name"`
	MimeType     string             `db:"mime_type" json:"mime_type"`
	SizeBytes    int64              `db:"size_bytes" json:"size_bytes"`
	Status       string             `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UploadedAt   pgtype.Timestamptz `db:"uploaded_at" json:"uploaded_at"`
	AttachedAt   pgtype.Timestamptz `db:"attached_at" json:"attached_at"`
	FailedAt     pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	RelaySchema  string             `db:"relay_schema" json:"relay_schema"`
}

type AttachmentUploadSession struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	AttachmentID uuid.UUID          `db:"attachment_id" json:"attachment_id"`
	OwnerUserID  uuid.UUID          `db:"owner_user_id" json:"owner_user_id"`
	Status       string             `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	FailedAt     pgtype.Timestamptz `db:"failed_at" json:"failed_at"`
}

type CryptoDevice struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	UserID                 uuid.UUID          `db:"user_id" json:"user_id"`
	Label                  string             `db:"label" json:"label"`
	Status                 string             `db:"status" json:"status"`
	LinkedByCryptoDeviceID pgtype.UUID        `db:"linked_by_crypto_device_id" json:"linked_by_crypto_device_id"`
	LastBundleVersion      pgtype.Int8        `db:"last_bundle_version" json:"last_bundle_version"`
	LastBundlePublishedAt  pgtype.Timestamptz `db:"last_bundle_published_at" json:"last_bundle_published_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	RevokedAt              pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason       pgtype.Text        `db:"revocation_reason" json:"revocation_reason"`
	RevokedByActor         pgtype.Text        `db:"revoked_by_actor" json:"revoked_by_actor"`
}

type CryptoDeviceBundle struct {
	CryptoDeviceID          uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	BundleVersion           int64              `db:"bundle_version" json:"bundle_version"`
	CryptoSuite             string             `db:"crypto_suite" json:"crypto_suite"`
	IdentityPublicKey       []byte             `db:"identity_public_key" json:"identity_public_key"`
	SignedPrekeyPublic      []byte             `db:"signed_prekey_public" json:"signed_prekey_public"`
	SignedPrekeyID          string             `db:"signed_prekey_id" json:"signed_prekey_id"`
	SignedPrekeySignature   []byte             `db:"signed_prekey_signature" json:"signed_prekey_signature"`
	KemPublicKey            []byte             `db:"kem_public_key" json:"kem_public_key"`
	KemKeyID                pgtype.Text        `db:"kem_key_id" json:"kem_key_id"`
	KemSignature            []byte             `db:"kem_signature" json:"kem_signature"`
	OneTimePrekeysTotal     int32              `db:"one_time_prekeys_total" json:"one_time_prekeys_total"`
	OneTimePrekeysAvailable int32              `db:"one_time_prekeys_available" json:"one_time_prekeys_available"`
	BundleDigest            []byte             `db:"bundle_digest" json:"bundle_digest"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SupersededAt            pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
}

type CryptoDeviceBundlePublishChallenge struct {
	CryptoDeviceID       uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	CurrentBundleVersion int64              `db:"current_bundle_version" json:"current_bundle_version"`
	CurrentBundleDigest  []byte             `db:"current_bundle_digest" json:"current_bundle_digest"`
	PublishChallenge     []byte             `db:"publish_challenge" json:"publish_challenge"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt            pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type CryptoDeviceLinkIntent struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
}

type DirectChat struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DirectChatEncryptedMessageDeliveriesV2 struct {
	MessageID               uuid.UUID          `db:"message_id" json:"message_id"`
	RecipientUserID         uuid.UUID          `db:"recipient_user_id" json:"recipient_user_id"`
	RecipientCryptoDeviceID uuid.UUID          `db:"recipient_crypto_device_id" json:"recipient_crypto_device_id"`
	TransportHeader         []byte             `db:"transport_header" json:"transport_header"`
	Ciphertext              []byte             `db:"ciphertext" json:"ciphertext"`
	CiphertextSizeBytes     int64              `db:"ciphertext_size_bytes" json:"ciphertext_size_bytes"`
	StoredAt                pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
}

type DirectChatEncryptedMessagePinsV2 struct {
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DirectChatEncryptedMessagesV2 struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID         uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	SenderCryptoDeviceID uuid.UUID          `db:"sender_crypto_device_id" json:"sender_crypto_device_id"`
	OperationKind        string             `db:"operation_kind" json:"operation_kind"`
	TargetMessageID      pgtype.UUID        `db:"target_message_id" json:"target_message_id"`
	Revision             int32              `db:"revision" json:"revision"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StoredAt             pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
}

type DirectChatEncryptedReadStatesV1 struct {
	ChatID                   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DirectChatMessage struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ChatID           uuid.UUID          `db:"chat_id" json:"chat_id"`
	SenderUserID     uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind             string             `db:"kind" json:"kind"`
	TextContent      string             `db:"text_content" json:"text_content"`
	MarkdownPolicy   string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EditedAt         pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	ReplyToMessageID pgtype.UUID        `db:"reply_to_message_id" json:"reply_to_message_id"`
	SearchVector     interface{}        `db:"search_vector" json:"search_vector"`
}

type DirectChatMessageTombstone struct {
	MessageID       uuid.UUID          `db:"message_id" json:"message_id"`
	ChatID          uuid.UUID          `db:"chat_id" json:"chat_id"`
	DeletedByUserID uuid.UUID          `db:"deleted_by_user_id" json:"deleted_by_user_id"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type DirectChatNotificationPreference struct {
	ChatID               uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	NotificationsEnabled bool               `db:"notifications_enabled" json:"notifications_enabled"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type DirectChatParticipant struct {
	ChatID   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID   uuid.UUID          `db:"user_id" json:"user_id"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type DirectChatPin struct {
	ChatID         uuid.UUID          `db:"chat_id" json:"chat_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DirectChatReadReceipt struct {
	ChatID                   uuid.UUID          `db:"chat_id" json:"chat_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Group struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupChatReadState struct {
	GroupID                  uuid.UUID          `db:"group_id" json:"group_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupEncryptedLanesV1 struct {
	GroupID       uuid.UUID          `db:"group_id" json:"group_id"`
	ThreadID      uuid.UUID          `db:"thread_id" json:"thread_id"`
	MlsGroupID    uuid.UUID          `db:"mls_group_id" json:"mls_group_id"`
	RosterVersion int64              `db:"roster_version" json:"roster_version"`
	ActivatedAt   pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupEncryptedMessageDeliveriesV1 struct {
	MessageID               uuid.UUID          `db:"message_id" json:"message_id"`
	RecipientUserID         uuid.UUID          `db:"recipient_user_id" json:"recipient_user_id"`
	RecipientCryptoDeviceID uuid.UUID          `db:"recipient_crypto_device_id" json:"recipient_crypto_device_id"`
	StoredAt                pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
}

type GroupEncryptedMessagePinsV1 struct {
	GroupID        uuid.UUID          `db:"group_id" json:"group_id"`
	MessageID      uuid.UUID          `db:"message_id" json:"message_id"`
	PinnedByUserID uuid.UUID          `db:"pinned_by_user_id" json:"pinned_by_user_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GroupEncryptedMessagesV1 struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	GroupID              uuid.UUID          `db:"group_id" json:"group_id"`
	ThreadID             uuid.UUID          `db:"thread_id" json:"thread_id"`
	MlsGroupID           uuid.UUID          `db:"mls_group_id" json:"mls_group_id"`
	RosterVersion        int64              `db:"roster_version" json:"roster_version"`
	SenderUserID         uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	SenderCryptoDeviceID uuid.UUID          `db:"sender_crypto_device_id" json:"sender_crypto_device_id"`
	OperationKind        string             `db:"operation_kind" json:"operation_kind"`
	TargetMessageID      pgtype.UUID        `db:"target_message_id" json:"target_message_id"`
	Revision             int32              `db:"revision" json:"revision"`
	Ciphertext           []byte             `db:"ciphertext" json:"ciphertext"`
	CiphertextSizeBytes  int64              `db:"ciphertext_size_bytes" json:"ciphertext_size_bytes"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StoredAt             pgtype.Timestamptz `db:"stored_at" json:"stored_at"`
}

type GroupEncryptedReadStatesV1 struct {
	GroupID                  uuid.UUID          `db:"group_id" json:"group_id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	LastReadMessageID        uuid.UUID          `db:"last_read_message_id" json:"last_read_message_id"`
	LastReadMessageCreatedAt pgtype.Timestamptz `db:"last_read_message_created_at" json:"last_read_message_created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupEncryptedRosterDevicesV1 struct {
	GroupID        uuid.UUID          `db:"group_id" json:"group_id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	CryptoDeviceID uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	RosterVersion  int64              `db:"roster_version" json:"roster_version"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupEncryptedRosterMembersV1 struct {
	GroupID           uuid.UUID          `db:"group_id" json:"group_id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	Role              string             `db:"role" json:"role"`
	IsWriteRestricted bool               `db:"is_write_restricted" json:"is_write_restricted"`
	RosterVersion     int64              `db:"roster_version" json:"roster_version"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupInviteLink struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	GroupID         uuid.UUID          `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Role            string             `db:"role" json:"role"`
	TokenHash       string             `db:"token_hash" json:"token_hash"`
	JoinCount       int32              `db:"join_count" json:"join_count"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DisabledAt      pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastJoinedAt    pgtype.Timestamptz `db:"last_joined_at" json:"last_joined_at"`
}

type GroupMembership struct {
	GroupID           uuid.UUID          `db:"group_id" json:"group_id"`
	UserID            uuid.UUID          `db:"user_id" json:"user_id"`
	Role              string             `db:"role" json:"role"`
	JoinedAt          pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	IsWriteRestricted bool               `db:"is_write_restricted" json:"is_write_restricted"`
	WriteRestrictedAt pgtype.Timestamptz `db:"write_restricted_at" json:"write_restricted_at"`
}

type GroupMessage struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	ThreadID         uuid.UUID          `db:"thread_id" json:"thread_id"`
	SenderUserID     uuid.UUID          `db:"sender_user_id" json:"sender_user_id"`
	Kind             string             `db:"kind" json:"kind"`
	TextContent      string             `db:"text_content" json:"text_content"`
	MarkdownPolicy   string             `db:"markdown_policy" json:"markdown_policy"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EditedAt         pgtype.Timestamptz `db:"edited_at" json:"edited_at"`
	ReplyToMessageID pgtype.UUID        `db:"reply_to_message_id" json:"reply_to_message_id"`
	SearchVector     interface{}        `db:"search_vector" json:"search_vector"`
}

type GroupNotificationPreference struct {
	GroupID              uuid.UUID          `db:"group_id" json:"group_id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	NotificationsEnabled bool               `db:"notifications_enabled" json:"notifications_enabled"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupThread struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	GroupID   uuid.UUID          `db:"group_id" json:"group_id"`
	ThreadKey string             `db:"thread_key" json:"thread_key"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MessageAttachment struct {
	AttachmentID               uuid.UUID          `db:"attachment_id" json:"attachment_id"`
	DirectChatMessageID        pgtype.UUID        `db:"direct_chat_message_id" json:"direct_chat_message_id"`
	GroupMessageID             pgtype.UUID        `db:"group_message_id" json:"group_message_id"`
	AttachedByUserID           uuid.UUID          `db:"attached_by_user_id" json:"attached_by_user_id"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EncryptedDirectMessageV2ID pgtype.UUID        `db:"encrypted_direct_message_v2_id" json:"encrypted_direct_message_v2_id"`
	EncryptedGroupMessageV1ID  pgtype.UUID        `db:"encrypted_group_message_v1_id" json:"encrypted_group_message_v1_id"`
}

type RtcCall struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ScopeType       string             `db:"scope_type" json:"scope_type"`
	DirectChatID    pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID         pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt         pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID   pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason       pgtype.Text        `db:"end_reason" json:"end_reason"`
}

type RtcCallParticipant struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	CallID       uuid.UUID          `db:"call_id" json:"call_id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	State        string             `db:"state" json:"state"`
	JoinedAt     pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt       pgtype.Timestamptz `db:"left_at" json:"left_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastSignalAt pgtype.Timestamptz `db:"last_signal_at" json:"last_signal_at"`
}

type User struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
}

type UserBlock struct {
	BlockerUserID uuid.UUID          `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID          `db:"blocked_user_id" json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserDevice struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Label      string             `db:"label" json:"label"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type UserFriendRequest struct {
	RequesterUserID uuid.UUID          `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID uuid.UUID          `db:"addressee_user_id" json:"addressee_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserFriendship struct {
	UserLowID  uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPasswordCredential struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type WebPushSubscription struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Endpoint       string             `db:"endpoint" json:"endpoint"`
	P256dhKey      string             `db:"p256dh_key" json:"p256dh_key"`
	AuthSecret     string             `db:"auth_secret" json:"auth_secret"`
	ExpirationTime pgtype.Timestamptz `db:"expiration_time" json:"expiration_time"`
	UserAgent      pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
