// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package rtcsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveParticipantsByCallID(ctx context.Context, callID uuid.UUID) (int64, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (RtcCall, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (RtcCallParticipant, error)
	EndCall(ctx context.Context, arg EndCallParams) (int64, error)
	GetActiveCallByDirectChatID(ctx context.Context, directChatID pgtype.UUID) (GetActiveCallByDirectChatIDRow, error)
	GetActiveCallByGroupID(ctx context.Context, groupID pgtype.UUID) (GetActiveCallByGroupIDRow, error)
	GetActiveParticipantByCallIDAndUserID(ctx context.Context, arg GetActiveParticipantByCallIDAndUserIDParams) (RtcCallParticipant, error)
	GetActiveParticipationByUserID(ctx context.Context, userID uuid.UUID) (GetActiveParticipationByUserIDRow, error)
	GetCallByID(ctx context.Context, id uuid.UUID) (GetCallByIDRow, error)
	LeaveActiveParticipantsByCallID(ctx context.Context, arg LeaveActiveParticipantsByCallIDParams) (int64, error)
	LeaveParticipant(ctx context.Context, arg LeaveParticipantParams) (int64, error)
	ListActiveParticipantsByCallID(ctx context.Context, callID uuid.UUID) ([]RtcCallParticipant, error)
	ListParticipantsByCallID(ctx context.Context, callID uuid.UUID) ([]RtcCallParticipant, error)
	TouchParticipantSignal(ctx context.Context, arg TouchParticipantSignalParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
