// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package rtcsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveParticipantsByCallID = `-- name: CountActiveParticipantsByCallID :one
SELECT COUNT(*)::bigint
FROM rtc_call_participants
WHERE call_id = $1
  AND state = 'active'
`

func (q *Queries) CountActiveParticipantsByCallID(ctx context.Context, callID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveParticipantsByCallID, callID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCall = `-- name: CreateCall :one
INSERT INTO rtc_calls (
    id,
    scope_type,
    direct_chat_id,
    group_id,
    created_by_user_id,
    status,
    created_at,
    started_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    id,
    scope_type,
    direct_chat_id,
    group_id,
    created_by_user_id,
    status,
    created_at,
    started_at,
    updated_at,
    ended_at,
    ended_by_user_id,
    end_reason
`

type CreateCallParams struct {
	ID              uuid.UUID          `db:"id" json:"id"`
	ScopeType       string             `db:"scope_type" json:"scope_type"`
	DirectChatID    pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID         pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status          string             `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCall(ctx context.Context, arg CreateCallParams) (RtcCall, error) {
	row := q.db.QueryRow(ctx, createCall,
		arg.ID,
		arg.ScopeType,
		arg.DirectChatID,
		arg.GroupID,
		arg.CreatedByUserID,
		arg.Status,
		arg.CreatedAt,
		arg.StartedAt,
		arg.UpdatedAt,
	)
	var i RtcCall
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.DirectChatID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.EndReason,
	)
	return i, err
}

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO rtc_call_participants (
    id,
    call_id,
    user_id,
    state,
    joined_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, call_id, user_id, state, joined_at, left_at, updated_at, last_signal_at
`

type CreateParticipantParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	CallID    uuid.UUID          `db:"call_id" json:"call_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	State     string             `db:"state" json:"state"`
	JoinedAt  pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (RtcCallParticipant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.ID,
		arg.CallID,
		arg.UserID,
		arg.State,
		arg.JoinedAt,
		arg.UpdatedAt,
	)
	var i RtcCallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.State,
		&i.JoinedAt,
		&i.LeftAt,
		&i.UpdatedAt,
		&i.LastSignalAt,
	)
	return i, err
}

const endCall = `-- name: EndCall :execrows
UPDATE rtc_calls
SET
    status = 'ended',
    updated_at = $1,
    ended_at = $2,
    ended_by_user_id = $3,
    end_reason = $4
WHERE id = $5
  AND status = 'active'
`

type EndCallParams struct {
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt       pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason     pgtype.Text        `db:"end_reason" json:"end_reason"`
	ID            uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) EndCall(ctx context.Context, arg EndCallParams) (int64, error) {
	result, err := q.db.Exec(ctx, endCall,
		arg.UpdatedAt,
		arg.EndedAt,
		arg.EndedByUserID,
		arg.EndReason,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveCallByDirectChatID = `-- name: GetActiveCallByDirectChatID :one
SELECT
    c.id,
    c.scope_type,
    c.direct_chat_id,
    c.group_id,
    c.created_by_user_id,
    c.status,
    c.created_at,
    c.started_at,
    c.updated_at,
    c.ended_at,
    c.ended_by_user_id,
    c.end_reason,
    COALESCE(active.active_participant_count, 0)::bigint AS active_participant_count
FROM rtc_calls c
LEFT JOIN (
    SELECT call_id, COUNT(*)::bigint AS active_participant_count
    FROM rtc_call_participants
    WHERE state = 'active'
    GROUP BY call_id
) active ON active.call_id = c.id
WHERE c.direct_chat_id = $1
  AND c.status = 'active'
`

type GetActiveCallByDirectChatIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	ScopeType              string             `db:"scope_type" json:"scope_type"`
	DirectChatID           pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID                pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID        uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status                 string             `db:"status" json:"status"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID          pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason              pgtype.Text        `db:"end_reason" json:"end_reason"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) GetActiveCallByDirectChatID(ctx context.Context, directChatID pgtype.UUID) (GetActiveCallByDirectChatIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveCallByDirectChatID, directChatID)
	var i GetActiveCallByDirectChatIDRow
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.DirectChatID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.EndReason,
		&i.ActiveParticipantCount,
	)
	return i, err
}

const getActiveCallByGroupID = `-- name: GetActiveCallByGroupID :one
SELECT
    c.id,
    c.scope_type,
    c.direct_chat_id,
    c.group_id,
    c.created_by_user_id,
    c.status,
    c.created_at,
    c.started_at,
    c.updated_at,
    c.ended_at,
    c.ended_by_user_id,
    c.end_reason,
    COALESCE(active.active_participant_count, 0)::bigint AS active_participant_count
FROM rtc_calls c
LEFT JOIN (
    SELECT call_id, COUNT(*)::bigint AS active_participant_count
    FROM rtc_call_participants
    WHERE state = 'active'
    GROUP BY call_id
) active ON active.call_id = c.id
WHERE c.group_id = $1
  AND c.status = 'active'
`

type GetActiveCallByGroupIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	ScopeType              string             `db:"scope_type" json:"scope_type"`
	DirectChatID           pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID                pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID        uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status                 string             `db:"status" json:"status"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID          pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason              pgtype.Text        `db:"end_reason" json:"end_reason"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) GetActiveCallByGroupID(ctx context.Context, groupID pgtype.UUID) (GetActiveCallByGroupIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveCallByGroupID, groupID)
	var i GetActiveCallByGroupIDRow
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.DirectChatID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.EndReason,
		&i.ActiveParticipantCount,
	)
	return i, err
}

const getActiveParticipantByCallIDAndUserID = `-- name: GetActiveParticipantByCallIDAndUserID :one
SELECT id, call_id, user_id, state, joined_at, left_at, updated_at, last_signal_at
FROM rtc_call_participants
WHERE call_id = $1
  AND user_id = $2
  AND state = 'active'
`

type GetActiveParticipantByCallIDAndUserIDParams struct {
	CallID uuid.UUID `db:"call_id" json:"call_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetActiveParticipantByCallIDAndUserID(ctx context.Context, arg GetActiveParticipantByCallIDAndUserIDParams) (RtcCallParticipant, error) {
	row := q.db.QueryRow(ctx, getActiveParticipantByCallIDAndUserID, arg.CallID, arg.UserID)
	var i RtcCallParticipant
	err := row.Scan(
		&i.ID,
		&i.CallID,
		&i.UserID,
		&i.State,
		&i.JoinedAt,
		&i.LeftAt,
		&i.UpdatedAt,
		&i.LastSignalAt,
	)
	return i, err
}

const getActiveParticipationByUserID = `-- name: GetActiveParticipationByUserID :one
SELECT
    c.id,
    c.scope_type,
    c.direct_chat_id,
    c.group_id,
    c.created_by_user_id,
    c.status,
    c.created_at,
    c.started_at,
    c.updated_at,
    c.ended_at,
    c.ended_by_user_id,
    c.end_reason,
    p.id AS participant_id,
    p.user_id,
    p.state,
    p.joined_at,
    p.left_at,
    p.updated_at AS participant_updated_at,
    p.last_signal_at
FROM rtc_call_participants p
JOIN rtc_calls c ON c.id = p.call_id
WHERE p.user_id = $1
  AND p.state = 'active'
  AND c.status = 'active'
ORDER BY p.joined_at DESC, p.id DESC
LIMIT 1
`

type GetActiveParticipationByUserIDRow struct {
	ID                   uuid.UUID          `db:"id" json:"id"`
	ScopeType            string             `db:"scope_type" json:"scope_type"`
	DirectChatID         pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID              pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID      uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status               string             `db:"status" json:"status"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt              pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID        pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason            pgtype.Text        `db:"end_reason" json:"end_reason"`
	ParticipantID        uuid.UUID          `db:"participant_id" json:"participant_id"`
	UserID               uuid.UUID          `db:"user_id" json:"user_id"`
	State                string             `db:"state" json:"state"`
	JoinedAt             pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	LeftAt               pgtype.Timestamptz `db:"left_at" json:"left_at"`
	ParticipantUpdatedAt pgtype.Timestamptz `db:"participant_updated_at" json:"participant_updated_at"`
	LastSignalAt         pgtype.Timestamptz `db:"last_signal_at" json:"last_signal_at"`
}

func (q *Queries) GetActiveParticipationByUserID(ctx context.Context, userID uuid.UUID) (GetActiveParticipationByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getActiveParticipationByUserID, userID)
	var i GetActiveParticipationByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.DirectChatID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.EndReason,
		&i.ParticipantID,
		&i.UserID,
		&i.State,
		&i.JoinedAt,
		&i.LeftAt,
		&i.ParticipantUpdatedAt,
		&i.LastSignalAt,
	)
	return i, err
}

const getCallByID = `-- name: GetCallByID :one
SELECT
    c.id,
    c.scope_type,
    c.direct_chat_id,
    c.group_id,
    c.created_by_user_id,
    c.status,
    c.created_at,
    c.started_at,
    c.updated_at,
    c.ended_at,
    c.ended_by_user_id,
    c.end_reason,
    COALESCE(active.active_participant_count, 0)::bigint AS active_participant_count
FROM rtc_calls c
LEFT JOIN (
    SELECT call_id, COUNT(*)::bigint AS active_participant_count
    FROM rtc_call_participants
    WHERE state = 'active'
    GROUP BY call_id
) active ON active.call_id = c.id
WHERE c.id = $1
`

type GetCallByIDRow struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	ScopeType              string             `db:"scope_type" json:"scope_type"`
	DirectChatID           pgtype.UUID        `db:"direct_chat_id" json:"direct_chat_id"`
	GroupID                pgtype.UUID        `db:"group_id" json:"group_id"`
	CreatedByUserID        uuid.UUID          `db:"created_by_user_id" json:"created_by_user_id"`
	Status                 string             `db:"status" json:"status"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt              pgtype.Timestamptz `db:"started_at" json:"started_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndedAt                pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	EndedByUserID          pgtype.UUID        `db:"ended_by_user_id" json:"ended_by_user_id"`
	EndReason              pgtype.Text        `db:"end_reason" json:"end_reason"`
	ActiveParticipantCount int64              `db:"active_participant_count" json:"active_participant_count"`
}

func (q *Queries) GetCallByID(ctx context.Context, id uuid.UUID) (GetCallByIDRow, error) {
	row := q.db.QueryRow(ctx, getCallByID, id)
	var i GetCallByIDRow
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.DirectChatID,
		&i.GroupID,
		&i.CreatedByUserID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.EndedAt,
		&i.EndedByUserID,
		&i.EndReason,
		&i.ActiveParticipantCount,
	)
	return i, err
}

const leaveActiveParticipantsByCallID = `-- name: LeaveActiveParticipantsByCallID :execrows
UPDATE rtc_call_participants
SET
    state = 'left',
    left_at = $1,
    updated_at = $2
WHERE call_id = $3
  AND state = 'active'
`

type LeaveActiveParticipantsByCallIDParams struct {
	LeftAt    pgtype.Timestamptz `db:"left_at" json:"left_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CallID    uuid.UUID          `db:"call_id" json:"call_id"`
}

func (q *Queries) LeaveActiveParticipantsByCallID(ctx context.Context, arg LeaveActiveParticipantsByCallIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveActiveParticipantsByCallID, arg.LeftAt, arg.UpdatedAt, arg.CallID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const leaveParticipant = `-- name: LeaveParticipant :execrows
UPDATE rtc_call_participants
SET
    state = 'left',
    left_at = $1,
    updated_at = $2
WHERE id = $3
  AND state = 'active'
`

type LeaveParticipantParams struct {
	LeftAt    pgtype.Timestamptz `db:"left_at" json:"left_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID        uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) LeaveParticipant(ctx context.Context, arg LeaveParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, leaveParticipant, arg.LeftAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveParticipantsByCallID = `-- name: ListActiveParticipantsByCallID :many
SELECT id, call_id, user_id, state, joined_at, left_at, updated_at, last_signal_at
FROM rtc_call_participants
WHERE call_id = $1
  AND state = 'active'
ORDER BY joined_at ASC, id ASC
`

func (q *Queries) ListActiveParticipantsByCallID(ctx context.Context, callID uuid.UUID) ([]RtcCallParticipant, error) {
	rows, err := q.db.Query(ctx, listActiveParticipantsByCallID, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RtcCallParticipant
	for rows.Next() {
		var i RtcCallParticipant
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.State,
			&i.JoinedAt,
			&i.LeftAt,
			&i.UpdatedAt,
			&i.LastSignalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByCallID = `-- name: ListParticipantsByCallID :many
SELECT id, call_id, user_id, state, joined_at, left_at, updated_at, last_signal_at
FROM rtc_call_participants
WHERE call_id = $1
ORDER BY joined_at ASC, id ASC
`

func (q *Queries) ListParticipantsByCallID(ctx context.Context, callID uuid.UUID) ([]RtcCallParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipantsByCallID, callID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RtcCallParticipant
	for rows.Next() {
		var i RtcCallParticipant
		if err := rows.Scan(
			&i.ID,
			&i.CallID,
			&i.UserID,
			&i.State,
			&i.JoinedAt,
			&i.LeftAt,
			&i.UpdatedAt,
			&i.LastSignalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchParticipantSignal = `-- name: TouchParticipantSignal :execrows
UPDATE rtc_call_participants
SET
    last_signal_at = $1,
    updated_at = $2
WHERE id = $3
  AND state = 'active'
`

type TouchParticipantSignalParams struct {
	LastSignalAt pgtype.Timestamptz `db:"last_signal_at" json:"last_signal_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID           uuid.UUID          `db:"id" json:"id"`
}

func (q *Queries) TouchParticipantSignal(ctx context.Context, arg TouchParticipantSignalParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchParticipantSignal, arg.LastSignalAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
