// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crypto_devices.sql

package identitysqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateCryptoDevice = `-- name: ActivateCryptoDevice :one
UPDATE crypto_devices
SET
    status = 'active',
    activated_at = $3,
    linked_by_crypto_device_id = $4
WHERE id = $1 AND user_id = $2 AND status = 'pending_link' AND revoked_at IS NULL
RETURNING
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
`

type ActivateCryptoDeviceParams struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	UserID                 uuid.UUID          `db:"user_id" json:"user_id"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	LinkedByCryptoDeviceID pgtype.UUID        `db:"linked_by_crypto_device_id" json:"linked_by_crypto_device_id"`
}

func (q *Queries) ActivateCryptoDevice(ctx context.Context, arg ActivateCryptoDeviceParams) (CryptoDevice, error) {
	row := q.db.QueryRow(ctx, activateCryptoDevice,
		arg.ID,
		arg.UserID,
		arg.ActivatedAt,
		arg.LinkedByCryptoDeviceID,
	)
	var i CryptoDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.LinkedByCryptoDeviceID,
		&i.LastBundleVersion,
		&i.LastBundlePublishedAt,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.RevokedByActor,
	)
	return i, err
}

const approveCryptoDeviceLinkIntentByIDAndUserID = `-- name: ApproveCryptoDeviceLinkIntentByIDAndUserID :one
UPDATE crypto_device_link_intents
SET
    status = 'approved',
    approved_at = $3,
    approved_by_crypto_device_id = $4
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
`

type ApproveCryptoDeviceLinkIntentByIDAndUserIDParams struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

type ApproveCryptoDeviceLinkIntentByIDAndUserIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) ApproveCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg ApproveCryptoDeviceLinkIntentByIDAndUserIDParams) (ApproveCryptoDeviceLinkIntentByIDAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, approveCryptoDeviceLinkIntentByIDAndUserID,
		arg.ID,
		arg.UserID,
		arg.ApprovedAt,
		arg.ApprovedByCryptoDeviceID,
	)
	var i ApproveCryptoDeviceLinkIntentByIDAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PendingCryptoDeviceID,
		&i.Status,
		&i.BundleDigest,
		&i.ApprovalChallenge,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.ApprovedByCryptoDeviceID,
	)
	return i, err
}

const createCryptoDevice = `-- name: CreateCryptoDevice :one
INSERT INTO crypto_devices (
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
`

type CreateCryptoDeviceParams struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	UserID                 uuid.UUID          `db:"user_id" json:"user_id"`
	Label                  string             `db:"label" json:"label"`
	Status                 string             `db:"status" json:"status"`
	LinkedByCryptoDeviceID pgtype.UUID        `db:"linked_by_crypto_device_id" json:"linked_by_crypto_device_id"`
	LastBundleVersion      pgtype.Int8        `db:"last_bundle_version" json:"last_bundle_version"`
	LastBundlePublishedAt  pgtype.Timestamptz `db:"last_bundle_published_at" json:"last_bundle_published_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	RevokedAt              pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason       pgtype.Text        `db:"revocation_reason" json:"revocation_reason"`
	RevokedByActor         pgtype.Text        `db:"revoked_by_actor" json:"revoked_by_actor"`
}

func (q *Queries) CreateCryptoDevice(ctx context.Context, arg CreateCryptoDeviceParams) (CryptoDevice, error) {
	row := q.db.QueryRow(ctx, createCryptoDevice,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.Status,
		arg.LinkedByCryptoDeviceID,
		arg.LastBundleVersion,
		arg.LastBundlePublishedAt,
		arg.CreatedAt,
		arg.ActivatedAt,
		arg.RevokedAt,
		arg.RevocationReason,
		arg.RevokedByActor,
	)
	var i CryptoDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.LinkedByCryptoDeviceID,
		&i.LastBundleVersion,
		&i.LastBundlePublishedAt,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.RevokedByActor,
	)
	return i, err
}

const createCryptoDeviceBundle = `-- name: CreateCryptoDeviceBundle :one
INSERT INTO crypto_device_bundles (
    crypto_device_id,
    bundle_version,
    crypto_suite,
    identity_public_key,
    signed_prekey_public,
    signed_prekey_id,
    signed_prekey_signature,
    kem_public_key,
    kem_key_id,
    kem_signature,
    one_time_prekeys_total,
    one_time_prekeys_available,
    bundle_digest,
    published_at,
    expires_at,
    superseded_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING
    crypto_device_id,
    bundle_version,
    crypto_suite,
    identity_public_key,
    signed_prekey_public,
    signed_prekey_id,
    signed_prekey_signature,
    kem_public_key,
    kem_key_id,
    kem_signature,
    one_time_prekeys_total,
    one_time_prekeys_available,
    bundle_digest,
    published_at,
    expires_at,
    superseded_at
`

type CreateCryptoDeviceBundleParams struct {
	CryptoDeviceID          uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	BundleVersion           int64              `db:"bundle_version" json:"bundle_version"`
	CryptoSuite             string             `db:"crypto_suite" json:"crypto_suite"`
	IdentityPublicKey       []byte             `db:"identity_public_key" json:"identity_public_key"`
	SignedPrekeyPublic      []byte             `db:"signed_prekey_public" json:"signed_prekey_public"`
	SignedPrekeyID          string             `db:"signed_prekey_id" json:"signed_prekey_id"`
	SignedPrekeySignature   []byte             `db:"signed_prekey_signature" json:"signed_prekey_signature"`
	KemPublicKey            []byte             `db:"kem_public_key" json:"kem_public_key"`
	KemKeyID                pgtype.Text        `db:"kem_key_id" json:"kem_key_id"`
	KemSignature            []byte             `db:"kem_signature" json:"kem_signature"`
	OneTimePrekeysTotal     int32              `db:"one_time_prekeys_total" json:"one_time_prekeys_total"`
	OneTimePrekeysAvailable int32              `db:"one_time_prekeys_available" json:"one_time_prekeys_available"`
	BundleDigest            []byte             `db:"bundle_digest" json:"bundle_digest"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SupersededAt            pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
}

func (q *Queries) CreateCryptoDeviceBundle(ctx context.Context, arg CreateCryptoDeviceBundleParams) (CryptoDeviceBundle, error) {
	row := q.db.QueryRow(ctx, createCryptoDeviceBundle,
		arg.CryptoDeviceID,
		arg.BundleVersion,
		arg.CryptoSuite,
		arg.IdentityPublicKey,
		arg.SignedPrekeyPublic,
		arg.SignedPrekeyID,
		arg.SignedPrekeySignature,
		arg.KemPublicKey,
		arg.KemKeyID,
		arg.KemSignature,
		arg.OneTimePrekeysTotal,
		arg.OneTimePrekeysAvailable,
		arg.BundleDigest,
		arg.PublishedAt,
		arg.ExpiresAt,
		arg.SupersededAt,
	)
	var i CryptoDeviceBundle
	err := row.Scan(
		&i.CryptoDeviceID,
		&i.BundleVersion,
		&i.CryptoSuite,
		&i.IdentityPublicKey,
		&i.SignedPrekeyPublic,
		&i.SignedPrekeyID,
		&i.SignedPrekeySignature,
		&i.KemPublicKey,
		&i.KemKeyID,
		&i.KemSignature,
		&i.OneTimePrekeysTotal,
		&i.OneTimePrekeysAvailable,
		&i.BundleDigest,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.SupersededAt,
	)
	return i, err
}

const createCryptoDeviceLinkIntent = `-- name: CreateCryptoDeviceLinkIntent :one
INSERT INTO crypto_device_link_intents (
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
`

type CreateCryptoDeviceLinkIntentParams struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

type CreateCryptoDeviceLinkIntentRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) CreateCryptoDeviceLinkIntent(ctx context.Context, arg CreateCryptoDeviceLinkIntentParams) (CreateCryptoDeviceLinkIntentRow, error) {
	row := q.db.QueryRow(ctx, createCryptoDeviceLinkIntent,
		arg.ID,
		arg.UserID,
		arg.PendingCryptoDeviceID,
		arg.Status,
		arg.BundleDigest,
		arg.ApprovalChallenge,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ApprovedAt,
		arg.ExpiredAt,
		arg.ApprovedByCryptoDeviceID,
	)
	var i CreateCryptoDeviceLinkIntentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PendingCryptoDeviceID,
		&i.Status,
		&i.BundleDigest,
		&i.ApprovalChallenge,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.ApprovedByCryptoDeviceID,
	)
	return i, err
}

const expireCryptoDeviceLinkIntentByIDAndUserID = `-- name: ExpireCryptoDeviceLinkIntentByIDAndUserID :one
UPDATE crypto_device_link_intents
SET
    status = 'expired',
    expired_at = $3
WHERE id = $1 AND user_id = $2 AND status = 'pending'
RETURNING
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
`

type ExpireCryptoDeviceLinkIntentByIDAndUserIDParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	ExpiredAt pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
}

type ExpireCryptoDeviceLinkIntentByIDAndUserIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) ExpireCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg ExpireCryptoDeviceLinkIntentByIDAndUserIDParams) (ExpireCryptoDeviceLinkIntentByIDAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, expireCryptoDeviceLinkIntentByIDAndUserID, arg.ID, arg.UserID, arg.ExpiredAt)
	var i ExpireCryptoDeviceLinkIntentByIDAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PendingCryptoDeviceID,
		&i.Status,
		&i.BundleDigest,
		&i.ApprovalChallenge,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.ApprovedByCryptoDeviceID,
	)
	return i, err
}

const expirePendingCryptoDeviceLinkIntentsByDeviceID = `-- name: ExpirePendingCryptoDeviceLinkIntentsByDeviceID :execrows
UPDATE crypto_device_link_intents
SET
    status = 'expired',
    expired_at = $2
WHERE pending_crypto_device_id = $1 AND status = 'pending'
`

type ExpirePendingCryptoDeviceLinkIntentsByDeviceIDParams struct {
	PendingCryptoDeviceID uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	ExpiredAt             pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
}

func (q *Queries) ExpirePendingCryptoDeviceLinkIntentsByDeviceID(ctx context.Context, arg ExpirePendingCryptoDeviceLinkIntentsByDeviceIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, expirePendingCryptoDeviceLinkIntentsByDeviceID, arg.PendingCryptoDeviceID, arg.ExpiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireStaleCryptoDeviceLinkIntentsByUserID = `-- name: ExpireStaleCryptoDeviceLinkIntentsByUserID :execrows
UPDATE crypto_device_link_intents
SET
    status = 'expired',
    expired_at = $2
WHERE user_id = $1 AND status = 'pending' AND expires_at <= $2
`

type ExpireStaleCryptoDeviceLinkIntentsByUserIDParams struct {
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	ExpiredAt pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
}

func (q *Queries) ExpireStaleCryptoDeviceLinkIntentsByUserID(ctx context.Context, arg ExpireStaleCryptoDeviceLinkIntentsByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireStaleCryptoDeviceLinkIntentsByUserID, arg.UserID, arg.ExpiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCryptoDeviceByIDAndUserID = `-- name: GetCryptoDeviceByIDAndUserID :one
SELECT
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
FROM crypto_devices
WHERE id = $1 AND user_id = $2
`

type GetCryptoDeviceByIDAndUserIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCryptoDeviceByIDAndUserID(ctx context.Context, arg GetCryptoDeviceByIDAndUserIDParams) (CryptoDevice, error) {
	row := q.db.QueryRow(ctx, getCryptoDeviceByIDAndUserID, arg.ID, arg.UserID)
	var i CryptoDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.LinkedByCryptoDeviceID,
		&i.LastBundleVersion,
		&i.LastBundlePublishedAt,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.RevokedByActor,
	)
	return i, err
}

const getCryptoDeviceLinkIntentByIDAndUserID = `-- name: GetCryptoDeviceLinkIntentByIDAndUserID :one
SELECT
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
FROM crypto_device_link_intents
WHERE id = $1 AND user_id = $2
`

type GetCryptoDeviceLinkIntentByIDAndUserIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetCryptoDeviceLinkIntentByIDAndUserIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) GetCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg GetCryptoDeviceLinkIntentByIDAndUserIDParams) (GetCryptoDeviceLinkIntentByIDAndUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCryptoDeviceLinkIntentByIDAndUserID, arg.ID, arg.UserID)
	var i GetCryptoDeviceLinkIntentByIDAndUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PendingCryptoDeviceID,
		&i.Status,
		&i.BundleDigest,
		&i.ApprovalChallenge,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.ApprovedByCryptoDeviceID,
	)
	return i, err
}

const getCryptoDeviceRegistryStatsByUserID = `-- name: GetCryptoDeviceRegistryStatsByUserID :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(*) FILTER (WHERE status = 'active')::bigint AS active_count,
    COUNT(*) FILTER (WHERE status = 'pending_link')::bigint AS pending_count
FROM crypto_devices
WHERE user_id = $1
`

type GetCryptoDeviceRegistryStatsByUserIDRow struct {
	TotalCount   int64 `db:"total_count" json:"total_count"`
	ActiveCount  int64 `db:"active_count" json:"active_count"`
	PendingCount int64 `db:"pending_count" json:"pending_count"`
}

func (q *Queries) GetCryptoDeviceRegistryStatsByUserID(ctx context.Context, userID uuid.UUID) (GetCryptoDeviceRegistryStatsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCryptoDeviceRegistryStatsByUserID, userID)
	var i GetCryptoDeviceRegistryStatsByUserIDRow
	err := row.Scan(&i.TotalCount, &i.ActiveCount, &i.PendingCount)
	return i, err
}

const getCurrentCryptoDeviceBundleByDeviceID = `-- name: GetCurrentCryptoDeviceBundleByDeviceID :one
SELECT
    crypto_device_id,
    bundle_version,
    crypto_suite,
    identity_public_key,
    signed_prekey_public,
    signed_prekey_id,
    signed_prekey_signature,
    kem_public_key,
    kem_key_id,
    kem_signature,
    one_time_prekeys_total,
    one_time_prekeys_available,
    bundle_digest,
    published_at,
    expires_at,
    superseded_at
FROM crypto_device_bundles
WHERE crypto_device_id = $1 AND superseded_at IS NULL
`

func (q *Queries) GetCurrentCryptoDeviceBundleByDeviceID(ctx context.Context, cryptoDeviceID uuid.UUID) (CryptoDeviceBundle, error) {
	row := q.db.QueryRow(ctx, getCurrentCryptoDeviceBundleByDeviceID, cryptoDeviceID)
	var i CryptoDeviceBundle
	err := row.Scan(
		&i.CryptoDeviceID,
		&i.BundleVersion,
		&i.CryptoSuite,
		&i.IdentityPublicKey,
		&i.SignedPrekeyPublic,
		&i.SignedPrekeyID,
		&i.SignedPrekeySignature,
		&i.KemPublicKey,
		&i.KemKeyID,
		&i.KemSignature,
		&i.OneTimePrekeysTotal,
		&i.OneTimePrekeysAvailable,
		&i.BundleDigest,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.SupersededAt,
	)
	return i, err
}

const getCurrentCryptoDeviceBundleByDeviceIDAndUserID = `-- name: GetCurrentCryptoDeviceBundleByDeviceIDAndUserID :one
SELECT
    b.crypto_device_id,
    b.bundle_version,
    b.crypto_suite,
    b.identity_public_key,
    b.signed_prekey_public,
    b.signed_prekey_id,
    b.signed_prekey_signature,
    b.kem_public_key,
    b.kem_key_id,
    b.kem_signature,
    b.one_time_prekeys_total,
    b.one_time_prekeys_available,
    b.bundle_digest,
    b.published_at,
    b.expires_at,
    b.superseded_at
FROM crypto_device_bundles AS b
JOIN crypto_devices AS d ON d.id = b.crypto_device_id
WHERE b.crypto_device_id = $1 AND d.user_id = $2 AND b.superseded_at IS NULL
`

type GetCurrentCryptoDeviceBundleByDeviceIDAndUserIDParams struct {
	CryptoDeviceID uuid.UUID `db:"crypto_device_id" json:"crypto_device_id"`
	UserID         uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCurrentCryptoDeviceBundleByDeviceIDAndUserID(ctx context.Context, arg GetCurrentCryptoDeviceBundleByDeviceIDAndUserIDParams) (CryptoDeviceBundle, error) {
	row := q.db.QueryRow(ctx, getCurrentCryptoDeviceBundleByDeviceIDAndUserID, arg.CryptoDeviceID, arg.UserID)
	var i CryptoDeviceBundle
	err := row.Scan(
		&i.CryptoDeviceID,
		&i.BundleVersion,
		&i.CryptoSuite,
		&i.IdentityPublicKey,
		&i.SignedPrekeyPublic,
		&i.SignedPrekeyID,
		&i.SignedPrekeySignature,
		&i.KemPublicKey,
		&i.KemKeyID,
		&i.KemSignature,
		&i.OneTimePrekeysTotal,
		&i.OneTimePrekeysAvailable,
		&i.BundleDigest,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.SupersededAt,
	)
	return i, err
}

const getPendingCryptoDeviceLinkIntentByDeviceID = `-- name: GetPendingCryptoDeviceLinkIntentByDeviceID :one
SELECT
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
FROM crypto_device_link_intents
WHERE pending_crypto_device_id = $1 AND status = 'pending'
`

type GetPendingCryptoDeviceLinkIntentByDeviceIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) GetPendingCryptoDeviceLinkIntentByDeviceID(ctx context.Context, pendingCryptoDeviceID uuid.UUID) (GetPendingCryptoDeviceLinkIntentByDeviceIDRow, error) {
	row := q.db.QueryRow(ctx, getPendingCryptoDeviceLinkIntentByDeviceID, pendingCryptoDeviceID)
	var i GetPendingCryptoDeviceLinkIntentByDeviceIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PendingCryptoDeviceID,
		&i.Status,
		&i.BundleDigest,
		&i.ApprovalChallenge,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ExpiredAt,
		&i.ApprovedByCryptoDeviceID,
	)
	return i, err
}

const listCryptoDeviceLinkIntentsByUserID = `-- name: ListCryptoDeviceLinkIntentsByUserID :many
SELECT
    id,
    user_id,
    pending_crypto_device_id,
    status,
    bundle_digest,
    approval_challenge,
    created_at,
    expires_at,
    approved_at,
    expired_at,
    approved_by_crypto_device_id
FROM crypto_device_link_intents
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListCryptoDeviceLinkIntentsByUserIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	ApprovalChallenge        []byte             `db:"approval_challenge" json:"approval_challenge"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

func (q *Queries) ListCryptoDeviceLinkIntentsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCryptoDeviceLinkIntentsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listCryptoDeviceLinkIntentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCryptoDeviceLinkIntentsByUserIDRow
	for rows.Next() {
		var i ListCryptoDeviceLinkIntentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PendingCryptoDeviceID,
			&i.Status,
			&i.BundleDigest,
			&i.ApprovalChallenge,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ApprovedAt,
			&i.ExpiredAt,
			&i.ApprovedByCryptoDeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCryptoDevicesByUserID = `-- name: ListCryptoDevicesByUserID :many
SELECT
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
FROM crypto_devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCryptoDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]CryptoDevice, error) {
	rows, err := q.db.Query(ctx, listCryptoDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CryptoDevice
	for rows.Next() {
		var i CryptoDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Status,
			&i.LinkedByCryptoDeviceID,
			&i.LastBundleVersion,
			&i.LastBundlePublishedAt,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.RevokedAt,
			&i.RevocationReason,
			&i.RevokedByActor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCryptoDeviceWithMetadata = `-- name: RevokeCryptoDeviceWithMetadata :one
UPDATE crypto_devices
SET
    status = 'revoked',
    revoked_at = $3,
    revocation_reason = $4,
    revoked_by_actor = $5
WHERE id = $1 AND user_id = $2 AND status <> 'revoked'
RETURNING
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
`

type RevokeCryptoDeviceWithMetadataParams struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason pgtype.Text        `db:"revocation_reason" json:"revocation_reason"`
	RevokedByActor   pgtype.Text        `db:"revoked_by_actor" json:"revoked_by_actor"`
}

func (q *Queries) RevokeCryptoDeviceWithMetadata(ctx context.Context, arg RevokeCryptoDeviceWithMetadataParams) (CryptoDevice, error) {
	row := q.db.QueryRow(ctx, revokeCryptoDeviceWithMetadata,
		arg.ID,
		arg.UserID,
		arg.RevokedAt,
		arg.RevocationReason,
		arg.RevokedByActor,
	)
	var i CryptoDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.LinkedByCryptoDeviceID,
		&i.LastBundleVersion,
		&i.LastBundlePublishedAt,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.RevokedByActor,
	)
	return i, err
}

const supersedeCurrentCryptoDeviceBundle = `-- name: SupersedeCurrentCryptoDeviceBundle :execrows
UPDATE crypto_device_bundles
SET superseded_at = $2
WHERE crypto_device_id = $1 AND superseded_at IS NULL
`

type SupersedeCurrentCryptoDeviceBundleParams struct {
	CryptoDeviceID uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	SupersededAt   pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
}

func (q *Queries) SupersedeCurrentCryptoDeviceBundle(ctx context.Context, arg SupersedeCurrentCryptoDeviceBundleParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeCurrentCryptoDeviceBundle, arg.CryptoDeviceID, arg.SupersededAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCryptoDeviceBundleTracking = `-- name: UpdateCryptoDeviceBundleTracking :one
UPDATE crypto_devices
SET
    last_bundle_version = $3,
    last_bundle_published_at = $4
WHERE id = $1 AND user_id = $2
RETURNING
    id,
    user_id,
    label,
    status,
    linked_by_crypto_device_id,
    last_bundle_version,
    last_bundle_published_at,
    created_at,
    activated_at,
    revoked_at,
    revocation_reason,
    revoked_by_actor
`

type UpdateCryptoDeviceBundleTrackingParams struct {
	ID                    uuid.UUID          `db:"id" json:"id"`
	UserID                uuid.UUID          `db:"user_id" json:"user_id"`
	LastBundleVersion     pgtype.Int8        `db:"last_bundle_version" json:"last_bundle_version"`
	LastBundlePublishedAt pgtype.Timestamptz `db:"last_bundle_published_at" json:"last_bundle_published_at"`
}

func (q *Queries) UpdateCryptoDeviceBundleTracking(ctx context.Context, arg UpdateCryptoDeviceBundleTrackingParams) (CryptoDevice, error) {
	row := q.db.QueryRow(ctx, updateCryptoDeviceBundleTracking,
		arg.ID,
		arg.UserID,
		arg.LastBundleVersion,
		arg.LastBundlePublishedAt,
	)
	var i CryptoDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Status,
		&i.LinkedByCryptoDeviceID,
		&i.LastBundleVersion,
		&i.LastBundlePublishedAt,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.RevokedAt,
		&i.RevocationReason,
		&i.RevokedByActor,
	)
	return i, err
}
