// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package identitysqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CryptoDevice struct {
	ID                     uuid.UUID          `db:"id" json:"id"`
	UserID                 uuid.UUID          `db:"user_id" json:"user_id"`
	Label                  string             `db:"label" json:"label"`
	Status                 string             `db:"status" json:"status"`
	LinkedByCryptoDeviceID pgtype.UUID        `db:"linked_by_crypto_device_id" json:"linked_by_crypto_device_id"`
	LastBundleVersion      pgtype.Int8        `db:"last_bundle_version" json:"last_bundle_version"`
	LastBundlePublishedAt  pgtype.Timestamptz `db:"last_bundle_published_at" json:"last_bundle_published_at"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ActivatedAt            pgtype.Timestamptz `db:"activated_at" json:"activated_at"`
	RevokedAt              pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevocationReason       pgtype.Text        `db:"revocation_reason" json:"revocation_reason"`
	RevokedByActor         pgtype.Text        `db:"revoked_by_actor" json:"revoked_by_actor"`
}

type CryptoDeviceBundle struct {
	CryptoDeviceID          uuid.UUID          `db:"crypto_device_id" json:"crypto_device_id"`
	BundleVersion           int64              `db:"bundle_version" json:"bundle_version"`
	CryptoSuite             string             `db:"crypto_suite" json:"crypto_suite"`
	IdentityPublicKey       []byte             `db:"identity_public_key" json:"identity_public_key"`
	SignedPrekeyPublic      []byte             `db:"signed_prekey_public" json:"signed_prekey_public"`
	SignedPrekeyID          string             `db:"signed_prekey_id" json:"signed_prekey_id"`
	SignedPrekeySignature   []byte             `db:"signed_prekey_signature" json:"signed_prekey_signature"`
	KemPublicKey            []byte             `db:"kem_public_key" json:"kem_public_key"`
	KemKeyID                pgtype.Text        `db:"kem_key_id" json:"kem_key_id"`
	KemSignature            []byte             `db:"kem_signature" json:"kem_signature"`
	OneTimePrekeysTotal     int32              `db:"one_time_prekeys_total" json:"one_time_prekeys_total"`
	OneTimePrekeysAvailable int32              `db:"one_time_prekeys_available" json:"one_time_prekeys_available"`
	BundleDigest            []byte             `db:"bundle_digest" json:"bundle_digest"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ExpiresAt               pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	SupersededAt            pgtype.Timestamptz `db:"superseded_at" json:"superseded_at"`
}

type CryptoDeviceLinkIntent struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	PendingCryptoDeviceID    uuid.UUID          `db:"pending_crypto_device_id" json:"pending_crypto_device_id"`
	Status                   string             `db:"status" json:"status"`
	BundleDigest             []byte             `db:"bundle_digest" json:"bundle_digest"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt                pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	ApprovedAt               pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
	ExpiredAt                pgtype.Timestamptz `db:"expired_at" json:"expired_at"`
	ApprovedByCryptoDeviceID pgtype.UUID        `db:"approved_by_crypto_device_id" json:"approved_by_crypto_device_id"`
}

type User struct {
	ID                      uuid.UUID          `db:"id" json:"id"`
	Login                   string             `db:"login" json:"login"`
	Nickname                string             `db:"nickname" json:"nickname"`
	AvatarUrl               pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                     pgtype.Text        `db:"bio" json:"bio"`
	Timezone                pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent           pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText              pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                pgtype.Date        `db:"birthday" json:"birthday"`
	Country                 pgtype.Text        `db:"country" json:"country"`
	City                    pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled     bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled         bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus         string             `db:"key_backup_status" json:"key_backup_status"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserBlock struct {
	BlockerUserID uuid.UUID          `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID          `db:"blocked_user_id" json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserDevice struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Label      string             `db:"label" json:"label"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type UserFriendRequest struct {
	RequesterUserID uuid.UUID          `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID uuid.UUID          `db:"addressee_user_id" json:"addressee_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserFriendship struct {
	UserLowID  uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPasswordCredential struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}
