// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package identitysqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO user_devices (
    id,
    user_id,
    label,
    created_at,
    last_seen_at,
    revoked_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, label, created_at, last_seen_at, revoked_at
`

type CreateDeviceParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Label      string             `db:"label" json:"label"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO user_friend_requests (
    requester_user_id,
    addressee_user_id,
    user_low_id,
    user_high_id,
    created_at
) VALUES ($1, $2, $3, $4, $5)
`

type CreateFriendRequestParams struct {
	RequesterUserID uuid.UUID          `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID uuid.UUID          `db:"addressee_user_id" json:"addressee_user_id"`
	UserLowID       uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID      uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendRequest,
		arg.RequesterUserID,
		arg.AddresseeUserID,
		arg.UserLowID,
		arg.UserHighID,
		arg.CreatedAt,
	)
	return err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO user_friendships (
    user_low_id,
    user_high_id,
    created_at
) VALUES ($1, $2, $3)
`

type CreateFriendshipParams struct {
	UserLowID  uuid.UUID          `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID          `db:"user_high_id" json:"user_high_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.Exec(ctx, createFriendship, arg.UserLowID, arg.UserHighID, arg.CreatedAt)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (
    id,
    user_id,
    device_id,
    token_hash,
    created_at,
    last_seen_at,
    revoked_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, device_id, token_hash, created_at, last_seen_at, revoked_at
`

type CreateSessionParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	TokenHash  string             `db:"token_hash" json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.RevokedAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    login,
    nickname,
    avatar_url,
    bio,
    timezone,
    profile_accent,
    status_text,
    birthday,
    country,
    city,
    read_receipts_enabled,
    presence_enabled,
    typing_visibility_enabled,
    key_backup_status,
    push_notifications_enabled,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
RETURNING
    id,
    login,
    nickname,
    avatar_url,
    bio,
    timezone,
    profile_accent,
    status_text,
    birthday,
    country,
    city,
    read_receipts_enabled,
    presence_enabled,
    typing_visibility_enabled,
    key_backup_status,
    push_notifications_enabled,
    created_at,
    updated_at
`

type CreateUserParams struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type CreateUserRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Login,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Bio,
		arg.Timezone,
		arg.ProfileAccent,
		arg.StatusText,
		arg.Birthday,
		arg.Country,
		arg.City,
		arg.ReadReceiptsEnabled,
		arg.PresenceEnabled,
		arg.TypingVisibilityEnabled,
		arg.KeyBackupStatus,
		arg.PushNotificationsEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserBlock = `-- name: CreateUserBlock :exec
INSERT INTO user_blocks (
    blocker_user_id,
    blocked_user_id,
    created_at
) VALUES ($1, $2, $3)
ON CONFLICT (blocker_user_id, blocked_user_id) DO NOTHING
`

type CreateUserBlockParams struct {
	BlockerUserID uuid.UUID          `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID          `db:"blocked_user_id" json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error {
	_, err := q.db.Exec(ctx, createUserBlock, arg.BlockerUserID, arg.BlockedUserID, arg.CreatedAt)
	return err
}

const createUserPasswordCredential = `-- name: CreateUserPasswordCredential :exec
INSERT INTO user_password_credentials (
    user_id,
    password_hash,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4)
`

type CreateUserPasswordCredentialParams struct {
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUserPasswordCredential(ctx context.Context, arg CreateUserPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, createUserPasswordCredential,
		arg.UserID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :execrows
DELETE FROM user_friend_requests
WHERE requester_user_id = $1 AND addressee_user_id = $2
`

type DeleteFriendRequestParams struct {
	RequesterUserID uuid.UUID `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID uuid.UUID `db:"addressee_user_id" json:"addressee_user_id"`
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendRequest, arg.RequesterUserID, arg.AddresseeUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFriendRequestsByPair = `-- name: DeleteFriendRequestsByPair :exec
DELETE FROM user_friend_requests
WHERE user_low_id = $1 AND user_high_id = $2
`

type DeleteFriendRequestsByPairParams struct {
	UserLowID  uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

func (q *Queries) DeleteFriendRequestsByPair(ctx context.Context, arg DeleteFriendRequestsByPairParams) error {
	_, err := q.db.Exec(ctx, deleteFriendRequestsByPair, arg.UserLowID, arg.UserHighID)
	return err
}

const deleteFriendshipByPair = `-- name: DeleteFriendshipByPair :execrows
DELETE FROM user_friendships
WHERE user_low_id = $1 AND user_high_id = $2
`

type DeleteFriendshipByPairParams struct {
	UserLowID  uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

func (q *Queries) DeleteFriendshipByPair(ctx context.Context, arg DeleteFriendshipByPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFriendshipByPair, arg.UserLowID, arg.UserHighID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserBlock = `-- name: DeleteUserBlock :execrows
DELETE FROM user_blocks
WHERE blocker_user_id = $1 AND blocked_user_id = $2
`

type DeleteUserBlockParams struct {
	BlockerUserID uuid.UUID `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID `db:"blocked_user_id" json:"blocked_user_id"`
}

func (q *Queries) DeleteUserBlock(ctx context.Context, arg DeleteUserBlockParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserBlock, arg.BlockerUserID, arg.BlockedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebPushSubscriptionByUserIDAndEndpoint = `-- name: DeleteWebPushSubscriptionByUserIDAndEndpoint :execrows
DELETE FROM web_push_subscriptions
WHERE user_id = $1 AND endpoint = $2
`

type DeleteWebPushSubscriptionByUserIDAndEndpointParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Endpoint string    `db:"endpoint" json:"endpoint"`
}

func (q *Queries) DeleteWebPushSubscriptionByUserIDAndEndpoint(ctx context.Context, arg DeleteWebPushSubscriptionByUserIDAndEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebPushSubscriptionByUserIDAndEndpoint, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebPushSubscriptionsByIDs = `-- name: DeleteWebPushSubscriptionsByIDs :execrows
DELETE FROM web_push_subscriptions
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteWebPushSubscriptionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebPushSubscriptionsByIDs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordCredentialByLogin = `-- name: GetPasswordCredentialByLogin :one
SELECT
    u.id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at,
    u.updated_at,
    c.password_hash,
    c.created_at AS password_created_at,
    c.updated_at AS password_updated_at
FROM users AS u
JOIN user_password_credentials AS c ON c.user_id = u.id
WHERE u.login = $1
`

type GetPasswordCredentialByLoginRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	PasswordHash             string             `db:"password_hash" json:"password_hash"`
	PasswordCreatedAt        pgtype.Timestamptz `db:"password_created_at" json:"password_created_at"`
	PasswordUpdatedAt        pgtype.Timestamptz `db:"password_updated_at" json:"password_updated_at"`
}

func (q *Queries) GetPasswordCredentialByLogin(ctx context.Context, login string) (GetPasswordCredentialByLoginRow, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByLogin, login)
	var i GetPasswordCredentialByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordCreatedAt,
		&i.PasswordUpdatedAt,
	)
	return i, err
}

const getSessionAuthByID = `-- name: GetSessionAuthByID :one
SELECT
    s.id AS session_id,
    s.user_id AS session_user_id,
    s.device_id AS session_device_id,
    s.token_hash,
    s.created_at AS session_created_at,
    s.last_seen_at AS session_last_seen_at,
    s.revoked_at AS session_revoked_at,
    d.id AS device_id,
    d.user_id AS device_user_id,
    d.label AS device_label,
    d.created_at AS device_created_at,
    d.last_seen_at AS device_last_seen_at,
    d.revoked_at AS device_revoked_at,
    u.id AS user_id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at AS user_created_at,
    u.updated_at AS user_updated_at
FROM user_sessions AS s
JOIN user_devices AS d ON d.id = s.device_id
JOIN users AS u ON u.id = s.user_id
WHERE s.id = $1
`

type GetSessionAuthByIDRow struct {
	SessionID                uuid.UUID          `db:"session_id" json:"session_id"`
	SessionUserID            uuid.UUID          `db:"session_user_id" json:"session_user_id"`
	SessionDeviceID          uuid.UUID          `db:"session_device_id" json:"session_device_id"`
	TokenHash                string             `db:"token_hash" json:"token_hash"`
	SessionCreatedAt         pgtype.Timestamptz `db:"session_created_at" json:"session_created_at"`
	SessionLastSeenAt        pgtype.Timestamptz `db:"session_last_seen_at" json:"session_last_seen_at"`
	SessionRevokedAt         pgtype.Timestamptz `db:"session_revoked_at" json:"session_revoked_at"`
	DeviceID                 uuid.UUID          `db:"device_id" json:"device_id"`
	DeviceUserID             uuid.UUID          `db:"device_user_id" json:"device_user_id"`
	DeviceLabel              string             `db:"device_label" json:"device_label"`
	DeviceCreatedAt          pgtype.Timestamptz `db:"device_created_at" json:"device_created_at"`
	DeviceLastSeenAt         pgtype.Timestamptz `db:"device_last_seen_at" json:"device_last_seen_at"`
	DeviceRevokedAt          pgtype.Timestamptz `db:"device_revoked_at" json:"device_revoked_at"`
	UserID                   uuid.UUID          `db:"user_id" json:"user_id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	UserCreatedAt            pgtype.Timestamptz `db:"user_created_at" json:"user_created_at"`
	UserUpdatedAt            pgtype.Timestamptz `db:"user_updated_at" json:"user_updated_at"`
}

func (q *Queries) GetSessionAuthByID(ctx context.Context, id uuid.UUID) (GetSessionAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionAuthByID, id)
	var i GetSessionAuthByIDRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionUserID,
		&i.SessionDeviceID,
		&i.TokenHash,
		&i.SessionCreatedAt,
		&i.SessionLastSeenAt,
		&i.SessionRevokedAt,
		&i.DeviceID,
		&i.DeviceUserID,
		&i.DeviceLabel,
		&i.DeviceCreatedAt,
		&i.DeviceLastSeenAt,
		&i.DeviceRevokedAt,
		&i.UserID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getSocialGraphState = `-- name: GetSocialGraphState :one
SELECT
    EXISTS (
        SELECT 1
        FROM user_blocks AS b
        WHERE (b.blocker_user_id = $1 AND b.blocked_user_id = $2)
           OR (b.blocker_user_id = $2 AND b.blocked_user_id = $1)
    ) AS has_block,
    EXISTS (
        SELECT 1
        FROM user_friendships AS f
        WHERE f.user_low_id = $3 AND f.user_high_id = $4
    ) AS are_friends,
    (
        SELECT fr.requester_user_id
        FROM user_friend_requests AS fr
        WHERE fr.user_low_id = $3 AND fr.user_high_id = $4
    ) AS requester_user_id,
    (
        SELECT fr.addressee_user_id
        FROM user_friend_requests AS fr
        WHERE fr.user_low_id = $3 AND fr.user_high_id = $4
    ) AS addressee_user_id,
    (
        SELECT fr.created_at
        FROM user_friend_requests AS fr
        WHERE fr.user_low_id = $3 AND fr.user_high_id = $4
    ) AS request_created_at
`

type GetSocialGraphStateParams struct {
	BlockerUserID uuid.UUID `db:"blocker_user_id" json:"blocker_user_id"`
	BlockedUserID uuid.UUID `db:"blocked_user_id" json:"blocked_user_id"`
	UserLowID     uuid.UUID `db:"user_low_id" json:"user_low_id"`
	UserHighID    uuid.UUID `db:"user_high_id" json:"user_high_id"`
}

type GetSocialGraphStateRow struct {
	HasBlock         bool               `db:"has_block" json:"has_block"`
	AreFriends       bool               `db:"are_friends" json:"are_friends"`
	RequesterUserID  uuid.UUID          `db:"requester_user_id" json:"requester_user_id"`
	AddresseeUserID  uuid.UUID          `db:"addressee_user_id" json:"addressee_user_id"`
	RequestCreatedAt pgtype.Timestamptz `db:"request_created_at" json:"request_created_at"`
}

func (q *Queries) GetSocialGraphState(ctx context.Context, arg GetSocialGraphStateParams) (GetSocialGraphStateRow, error) {
	row := q.db.QueryRow(ctx, getSocialGraphState,
		arg.BlockerUserID,
		arg.BlockedUserID,
		arg.UserLowID,
		arg.UserHighID,
	)
	var i GetSocialGraphStateRow
	err := row.Scan(
		&i.HasBlock,
		&i.AreFriends,
		&i.RequesterUserID,
		&i.AddresseeUserID,
		&i.RequestCreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    login,
    nickname,
    avatar_url,
    bio,
    timezone,
    profile_accent,
    status_text,
    birthday,
    country,
    city,
    read_receipts_enabled,
    presence_enabled,
    typing_visibility_enabled,
    key_backup_status,
    push_notifications_enabled,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT
    id,
    login,
    nickname,
    avatar_url,
    bio,
    timezone,
    profile_accent,
    status_text,
    birthday,
    country,
    city,
    read_receipts_enabled,
    presence_enabled,
    typing_visibility_enabled,
    key_backup_status,
    push_notifications_enabled,
    created_at,
    updated_at
FROM users
WHERE login = $1
`

type GetUserByLoginRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockedUsersByUserID = `-- name: ListBlockedUsersByUserID :many
SELECT
    b.created_at AS blocked_at,
    u.id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at,
    u.updated_at
FROM user_blocks AS b
JOIN users AS u ON u.id = b.blocked_user_id
WHERE b.blocker_user_id = $1
ORDER BY b.created_at DESC
`

type ListBlockedUsersByUserIDRow struct {
	BlockedAt                pgtype.Timestamptz `db:"blocked_at" json:"blocked_at"`
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListBlockedUsersByUserID(ctx context.Context, blockerUserID uuid.UUID) ([]ListBlockedUsersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listBlockedUsersByUserID, blockerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedUsersByUserIDRow
	for rows.Next() {
		var i ListBlockedUsersByUserIDRow
		if err := rows.Scan(
			&i.BlockedAt,
			&i.ID,
			&i.Login,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Bio,
			&i.Timezone,
			&i.ProfileAccent,
			&i.StatusText,
			&i.Birthday,
			&i.Country,
			&i.City,
			&i.ReadReceiptsEnabled,
			&i.PresenceEnabled,
			&i.TypingVisibilityEnabled,
			&i.KeyBackupStatus,
			&i.PushNotificationsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUserID = `-- name: ListDevicesByUserID :many
SELECT
    id,
    user_id,
    label,
    created_at,
    last_seen_at,
    revoked_at
FROM user_devices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsByUserID = `-- name: ListFriendsByUserID :many
SELECT
    f.created_at AS friends_since,
    u.id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at,
    u.updated_at
FROM user_friendships AS f
JOIN users AS u
    ON u.id = CASE
        WHEN f.user_low_id = $1 THEN f.user_high_id
        ELSE f.user_low_id
    END
WHERE f.user_low_id = $1 OR f.user_high_id = $1
ORDER BY f.created_at DESC
`

type ListFriendsByUserIDRow struct {
	FriendsSince             pgtype.Timestamptz `db:"friends_since" json:"friends_since"`
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListFriendsByUserID(ctx context.Context, userLowID uuid.UUID) ([]ListFriendsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByUserID, userLowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByUserIDRow
	for rows.Next() {
		var i ListFriendsByUserIDRow
		if err := rows.Scan(
			&i.FriendsSince,
			&i.ID,
			&i.Login,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Bio,
			&i.Timezone,
			&i.ProfileAccent,
			&i.StatusText,
			&i.Birthday,
			&i.Country,
			&i.City,
			&i.ReadReceiptsEnabled,
			&i.PresenceEnabled,
			&i.TypingVisibilityEnabled,
			&i.KeyBackupStatus,
			&i.PushNotificationsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequestsByUserID = `-- name: ListIncomingFriendRequestsByUserID :many
SELECT
    fr.created_at AS requested_at,
    u.id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at,
    u.updated_at
FROM user_friend_requests AS fr
JOIN users AS u ON u.id = fr.requester_user_id
WHERE fr.addressee_user_id = $1
ORDER BY fr.created_at DESC
`

type ListIncomingFriendRequestsByUserIDRow struct {
	RequestedAt              pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListIncomingFriendRequestsByUserID(ctx context.Context, addresseeUserID uuid.UUID) ([]ListIncomingFriendRequestsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequestsByUserID, addresseeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsByUserIDRow
	for rows.Next() {
		var i ListIncomingFriendRequestsByUserIDRow
		if err := rows.Scan(
			&i.RequestedAt,
			&i.ID,
			&i.Login,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Bio,
			&i.Timezone,
			&i.ProfileAccent,
			&i.StatusText,
			&i.Birthday,
			&i.Country,
			&i.City,
			&i.ReadReceiptsEnabled,
			&i.PresenceEnabled,
			&i.TypingVisibilityEnabled,
			&i.KeyBackupStatus,
			&i.PushNotificationsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequestsByUserID = `-- name: ListOutgoingFriendRequestsByUserID :many
SELECT
    fr.created_at AS requested_at,
    u.id,
    u.login,
    u.nickname,
    u.avatar_url,
    u.bio,
    u.timezone,
    u.profile_accent,
    u.status_text,
    u.birthday,
    u.country,
    u.city,
    u.read_receipts_enabled,
    u.presence_enabled,
    u.typing_visibility_enabled,
    u.key_backup_status,
    u.push_notifications_enabled,
    u.created_at,
    u.updated_at
FROM user_friend_requests AS fr
JOIN users AS u ON u.id = fr.addressee_user_id
WHERE fr.requester_user_id = $1
ORDER BY fr.created_at DESC
`

type ListOutgoingFriendRequestsByUserIDRow struct {
	RequestedAt              pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListOutgoingFriendRequestsByUserID(ctx context.Context, requesterUserID uuid.UUID) ([]ListOutgoingFriendRequestsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingFriendRequestsByUserID, requesterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutgoingFriendRequestsByUserIDRow
	for rows.Next() {
		var i ListOutgoingFriendRequestsByUserIDRow
		if err := rows.Scan(
			&i.RequestedAt,
			&i.ID,
			&i.Login,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Bio,
			&i.Timezone,
			&i.ProfileAccent,
			&i.StatusText,
			&i.Birthday,
			&i.Country,
			&i.City,
			&i.ReadReceiptsEnabled,
			&i.PresenceEnabled,
			&i.TypingVisibilityEnabled,
			&i.KeyBackupStatus,
			&i.PushNotificationsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT
    id,
    user_id,
    device_id,
    token_hash,
    created_at,
    last_seen_at,
    revoked_at
FROM user_sessions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebPushSubscriptionsByUserID = `-- name: ListWebPushSubscriptionsByUserID :many
SELECT
    id,
    user_id,
    endpoint,
    p256dh_key,
    auth_secret,
    expiration_time,
    user_agent,
    created_at,
    updated_at
FROM web_push_subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebPushSubscriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]WebPushSubscription, error) {
	rows, err := q.db.Query(ctx, listWebPushSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebPushSubscription
	for rows.Next() {
		var i WebPushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthSecret,
			&i.ExpirationTime,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE user_devices
SET revoked_at = $3
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDevice, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDeviceSessions = `-- name: RevokeDeviceSessions :exec
UPDATE user_sessions
SET revoked_at = $3
WHERE device_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceSessionsParams struct {
	DeviceID  uuid.UUID          `db:"device_id" json:"device_id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeDeviceSessions(ctx context.Context, arg RevokeDeviceSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeDeviceSessions, arg.DeviceID, arg.UserID, arg.RevokedAt)
	return err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE user_sessions
SET revoked_at = $3
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSessionAndDevice = `-- name: TouchSessionAndDevice :exec
WITH touched_session AS (
    UPDATE user_sessions AS s
    SET last_seen_at = $3
    WHERE s.id = $1 AND s.device_id = $2
), touched_device AS (
    UPDATE user_devices AS d
    SET last_seen_at = $3
    WHERE d.id = $2
)
SELECT 1
`

type TouchSessionAndDeviceParams struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	DeviceID   uuid.UUID          `db:"device_id" json:"device_id"`
	LastSeenAt pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) TouchSessionAndDevice(ctx context.Context, arg TouchSessionAndDeviceParams) error {
	_, err := q.db.Exec(ctx, touchSessionAndDevice, arg.ID, arg.DeviceID, arg.LastSeenAt)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    nickname = $2,
    avatar_url = $3,
    bio = $4,
    timezone = $5,
    profile_accent = $6,
    status_text = $7,
    birthday = $8,
    country = $9,
    city = $10,
    read_receipts_enabled = $11,
    presence_enabled = $12,
    typing_visibility_enabled = $13,
    key_backup_status = $14,
    push_notifications_enabled = $15,
    updated_at = $16
WHERE id = $1
RETURNING
    id,
    login,
    nickname,
    avatar_url,
    bio,
    timezone,
    profile_accent,
    status_text,
    birthday,
    country,
    city,
    read_receipts_enabled,
    presence_enabled,
    typing_visibility_enabled,
    key_backup_status,
    push_notifications_enabled,
    created_at,
    updated_at
`

type UpdateUserProfileParams struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type UpdateUserProfileRow struct {
	ID                       uuid.UUID          `db:"id" json:"id"`
	Login                    string             `db:"login" json:"login"`
	Nickname                 string             `db:"nickname" json:"nickname"`
	AvatarUrl                pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Bio                      pgtype.Text        `db:"bio" json:"bio"`
	Timezone                 pgtype.Text        `db:"timezone" json:"timezone"`
	ProfileAccent            pgtype.Text        `db:"profile_accent" json:"profile_accent"`
	StatusText               pgtype.Text        `db:"status_text" json:"status_text"`
	Birthday                 pgtype.Date        `db:"birthday" json:"birthday"`
	Country                  pgtype.Text        `db:"country" json:"country"`
	City                     pgtype.Text        `db:"city" json:"city"`
	ReadReceiptsEnabled      bool               `db:"read_receipts_enabled" json:"read_receipts_enabled"`
	PresenceEnabled          bool               `db:"presence_enabled" json:"presence_enabled"`
	TypingVisibilityEnabled  bool               `db:"typing_visibility_enabled" json:"typing_visibility_enabled"`
	KeyBackupStatus          string             `db:"key_backup_status" json:"key_backup_status"`
	PushNotificationsEnabled bool               `db:"push_notifications_enabled" json:"push_notifications_enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Bio,
		arg.Timezone,
		arg.ProfileAccent,
		arg.StatusText,
		arg.Birthday,
		arg.Country,
		arg.City,
		arg.ReadReceiptsEnabled,
		arg.PresenceEnabled,
		arg.TypingVisibilityEnabled,
		arg.KeyBackupStatus,
		arg.PushNotificationsEnabled,
		arg.UpdatedAt,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Bio,
		&i.Timezone,
		&i.ProfileAccent,
		&i.StatusText,
		&i.Birthday,
		&i.Country,
		&i.City,
		&i.ReadReceiptsEnabled,
		&i.PresenceEnabled,
		&i.TypingVisibilityEnabled,
		&i.KeyBackupStatus,
		&i.PushNotificationsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWebPushSubscription = `-- name: UpsertWebPushSubscription :exec
INSERT INTO web_push_subscriptions (
    id,
    user_id,
    endpoint,
    p256dh_key,
    auth_secret,
    expiration_time,
    user_agent,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (endpoint) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    p256dh_key = EXCLUDED.p256dh_key,
    auth_secret = EXCLUDED.auth_secret,
    expiration_time = EXCLUDED.expiration_time,
    user_agent = EXCLUDED.user_agent,
    updated_at = EXCLUDED.updated_at
`

type UpsertWebPushSubscriptionParams struct {
	ID             uuid.UUID          `db:"id" json:"id"`
	UserID         uuid.UUID          `db:"user_id" json:"user_id"`
	Endpoint       string             `db:"endpoint" json:"endpoint"`
	P256dhKey      string             `db:"p256dh_key" json:"p256dh_key"`
	AuthSecret     string             `db:"auth_secret" json:"auth_secret"`
	ExpirationTime pgtype.Timestamptz `db:"expiration_time" json:"expiration_time"`
	UserAgent      pgtype.Text        `db:"user_agent" json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertWebPushSubscription(ctx context.Context, arg UpsertWebPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertWebPushSubscription,
		arg.ID,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthSecret,
		arg.ExpirationTime,
		arg.UserAgent,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
