// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package identitysqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateCryptoDevice(ctx context.Context, arg ActivateCryptoDeviceParams) (CryptoDevice, error)
	ApproveCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg ApproveCryptoDeviceLinkIntentByIDAndUserIDParams) (ApproveCryptoDeviceLinkIntentByIDAndUserIDRow, error)
	CreateCryptoDevice(ctx context.Context, arg CreateCryptoDeviceParams) (CryptoDevice, error)
	CreateCryptoDeviceBundle(ctx context.Context, arg CreateCryptoDeviceBundleParams) (CryptoDeviceBundle, error)
	CreateCryptoDeviceLinkIntent(ctx context.Context, arg CreateCryptoDeviceLinkIntentParams) (CreateCryptoDeviceLinkIntentRow, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (UserDevice, error)
	CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserBlock(ctx context.Context, arg CreateUserBlockParams) error
	CreateUserPasswordCredential(ctx context.Context, arg CreateUserPasswordCredentialParams) error
	DeleteCryptoDeviceBundlePublishChallengeByDeviceID(ctx context.Context, cryptoDeviceID uuid.UUID) (int64, error)
	DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) (int64, error)
	DeleteFriendRequestsByPair(ctx context.Context, arg DeleteFriendRequestsByPairParams) error
	DeleteFriendshipByPair(ctx context.Context, arg DeleteFriendshipByPairParams) (int64, error)
	DeleteUserBlock(ctx context.Context, arg DeleteUserBlockParams) (int64, error)
	ExpireCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg ExpireCryptoDeviceLinkIntentByIDAndUserIDParams) (ExpireCryptoDeviceLinkIntentByIDAndUserIDRow, error)
	ExpirePendingCryptoDeviceLinkIntentsByDeviceID(ctx context.Context, arg ExpirePendingCryptoDeviceLinkIntentsByDeviceIDParams) (int64, error)
	ExpireStaleCryptoDeviceLinkIntentsByUserID(ctx context.Context, arg ExpireStaleCryptoDeviceLinkIntentsByUserIDParams) (int64, error)
	GetCryptoDeviceBundlePublishChallengeByDeviceID(ctx context.Context, cryptoDeviceID uuid.UUID) (CryptoDeviceBundlePublishChallenge, error)
	GetCryptoDeviceByIDAndUserID(ctx context.Context, arg GetCryptoDeviceByIDAndUserIDParams) (CryptoDevice, error)
	GetCryptoDeviceLinkIntentByIDAndUserID(ctx context.Context, arg GetCryptoDeviceLinkIntentByIDAndUserIDParams) (GetCryptoDeviceLinkIntentByIDAndUserIDRow, error)
	GetCryptoDeviceRegistryStatsByUserID(ctx context.Context, userID uuid.UUID) (GetCryptoDeviceRegistryStatsByUserIDRow, error)
	GetCurrentCryptoDeviceBundleByDeviceID(ctx context.Context, cryptoDeviceID uuid.UUID) (CryptoDeviceBundle, error)
	GetCurrentCryptoDeviceBundleByDeviceIDAndUserID(ctx context.Context, arg GetCurrentCryptoDeviceBundleByDeviceIDAndUserIDParams) (CryptoDeviceBundle, error)
	GetPasswordCredentialByLogin(ctx context.Context, login string) (GetPasswordCredentialByLoginRow, error)
	GetPendingCryptoDeviceLinkIntentByDeviceID(ctx context.Context, pendingCryptoDeviceID uuid.UUID) (GetPendingCryptoDeviceLinkIntentByDeviceIDRow, error)
	GetSessionAuthByID(ctx context.Context, id uuid.UUID) (GetSessionAuthByIDRow, error)
	GetSocialGraphState(ctx context.Context, arg GetSocialGraphStateParams) (GetSocialGraphStateRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	ListBlockedUsersByUserID(ctx context.Context, blockerUserID uuid.UUID) ([]ListBlockedUsersByUserIDRow, error)
	ListCryptoDeviceLinkIntentsByUserID(ctx context.Context, userID uuid.UUID) ([]ListCryptoDeviceLinkIntentsByUserIDRow, error)
	ListCryptoDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]CryptoDevice, error)
	ListDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error)
	ListFriendsByUserID(ctx context.Context, userLowID uuid.UUID) ([]ListFriendsByUserIDRow, error)
	ListIncomingFriendRequestsByUserID(ctx context.Context, addresseeUserID uuid.UUID) ([]ListIncomingFriendRequestsByUserIDRow, error)
	ListOutgoingFriendRequestsByUserID(ctx context.Context, requesterUserID uuid.UUID) ([]ListOutgoingFriendRequestsByUserIDRow, error)
	ListSessionsByUserID(ctx context.Context, userID uuid.UUID) ([]UserSession, error)
	RevokeCryptoDeviceWithMetadata(ctx context.Context, arg RevokeCryptoDeviceWithMetadataParams) (CryptoDevice, error)
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error)
	RevokeDeviceSessions(ctx context.Context, arg RevokeDeviceSessionsParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error)
	SupersedeCurrentCryptoDeviceBundle(ctx context.Context, arg SupersedeCurrentCryptoDeviceBundleParams) (int64, error)
	TouchSessionAndDevice(ctx context.Context, arg TouchSessionAndDeviceParams) error
	UpdateCryptoDeviceBundleTracking(ctx context.Context, arg UpdateCryptoDeviceBundleTrackingParams) (CryptoDevice, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertCryptoDeviceBundlePublishChallenge(ctx context.Context, arg UpsertCryptoDeviceBundlePublishChallengeParams) (CryptoDeviceBundlePublishChallenge, error)
}

var _ Querier = (*Queries)(nil)
