// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package identitysqlc

import (
	"context"
)

type Querier interface {
	// Foundation phase: sqlc подключён заранее, но доменные запросы появятся только на этапе Identity foundation.
	FoundationStatus(ctx context.Context) (string, error)
}

var _ Querier = (*Queries)(nil)
