// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package identitysqlc

import (
	"context"
)

const foundationStatus = `-- name: FoundationStatus :one

SELECT 'foundation'::text AS stage
`

// Foundation phase: sqlc подключён заранее, но доменные запросы появятся только на этапе Identity foundation.
func (q *Queries) FoundationStatus(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, foundationStatus)
	var stage string
	err := row.Scan(&stage)
	return stage, err
}
